// Code generated by protoc-gen-go. DO NOT EDIT.
// source: examples/banking/account/account.proto

package account

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Account is the saga.Instance for the account aggregate.
type Account struct {
	AccountId            string   `protobuf:"bytes,1,opt,name=account_id,json=accountId" json:"account_id,omitempty"`
	IsOpen               bool     `protobuf:"varint,2,opt,name=is_open,json=isOpen" json:"is_open,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Balance              int32    `protobuf:"varint,4,opt,name=balance" json:"balance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_c1717eb8bdeb1939, []int{0}
}
func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (dst *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(dst, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *Account) GetIsOpen() bool {
	if m != nil {
		return m.IsOpen
	}
	return false
}

func (m *Account) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Account) GetBalance() int32 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func init() {
	proto.RegisterType((*Account)(nil), "ax.examples.banking.Account")
}

func init() {
	proto.RegisterFile("examples/banking/account/account.proto", fileDescriptor_account_c1717eb8bdeb1939)
}

var fileDescriptor_account_c1717eb8bdeb1939 = []byte{
	// 165 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x4b, 0xad, 0x48, 0xcc,
	0x2d, 0xc8, 0x49, 0x2d, 0xd6, 0x4f, 0x4a, 0xcc, 0xcb, 0xce, 0xcc, 0x4b, 0xd7, 0x4f, 0x4c, 0x4e,
	0xce, 0x2f, 0xcd, 0x2b, 0x81, 0xd1, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0xc2, 0x89, 0x15,
	0x7a, 0x30, 0xa5, 0x7a, 0x50, 0xa5, 0x4a, 0xf9, 0x5c, 0xec, 0x8e, 0x10, 0x55, 0x42, 0xb2, 0x5c,
	0x5c, 0x50, 0x0d, 0xf1, 0x99, 0x29, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x9c, 0x50, 0x11,
	0xcf, 0x14, 0x21, 0x71, 0x2e, 0xf6, 0xcc, 0xe2, 0xf8, 0xfc, 0x82, 0xd4, 0x3c, 0x09, 0x26, 0x05,
	0x46, 0x0d, 0x8e, 0x20, 0xb6, 0xcc, 0x62, 0xff, 0x82, 0xd4, 0x3c, 0x21, 0x21, 0x2e, 0x96, 0xbc,
	0xc4, 0xdc, 0x54, 0x09, 0x66, 0xb0, 0x0e, 0x30, 0x5b, 0x48, 0x82, 0x8b, 0x3d, 0x29, 0x31, 0x27,
	0x31, 0x2f, 0x39, 0x55, 0x82, 0x45, 0x81, 0x51, 0x83, 0x35, 0x08, 0xc6, 0x75, 0xe2, 0x8c, 0x62,
	0x87, 0x9a, 0x99, 0xc4, 0x06, 0x76, 0x97, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x20, 0x34, 0x67,
	0x0e, 0xc1, 0x00, 0x00, 0x00,
}
