// Code generated by protoc-gen-go. DO NOT EDIT.
// source: src/axbolt/delayedmessage/delayedmessage.proto

package delayedmessage

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import ax "github.com/jmalloc/ax/src/ax"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// DelayedMessage is a container for holding delayed message-specific data that
// is serialized into the protobuf format before being persisted in a Bolt
// bucket.
type DelayedMessage struct {
	Envelope             *ax.EnvelopeProto `protobuf:"bytes,1,opt,name=Envelope,proto3" json:"Envelope,omitempty"`
	Operation            int32             `protobuf:"varint,7,opt,name=operation,proto3" json:"operation,omitempty"`
	DestinationEndpoint  string            `protobuf:"bytes,8,opt,name=destination_endpoint,json=destinationEndpoint,proto3" json:"destination_endpoint,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *DelayedMessage) Reset()         { *m = DelayedMessage{} }
func (m *DelayedMessage) String() string { return proto.CompactTextString(m) }
func (*DelayedMessage) ProtoMessage()    {}
func (*DelayedMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_delayedmessage_d65a2173b51c3030, []int{0}
}
func (m *DelayedMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelayedMessage.Unmarshal(m, b)
}
func (m *DelayedMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelayedMessage.Marshal(b, m, deterministic)
}
func (dst *DelayedMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelayedMessage.Merge(dst, src)
}
func (m *DelayedMessage) XXX_Size() int {
	return xxx_messageInfo_DelayedMessage.Size(m)
}
func (m *DelayedMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_DelayedMessage.DiscardUnknown(m)
}

var xxx_messageInfo_DelayedMessage proto.InternalMessageInfo

func (m *DelayedMessage) GetEnvelope() *ax.EnvelopeProto {
	if m != nil {
		return m.Envelope
	}
	return nil
}

func (m *DelayedMessage) GetOperation() int32 {
	if m != nil {
		return m.Operation
	}
	return 0
}

func (m *DelayedMessage) GetDestinationEndpoint() string {
	if m != nil {
		return m.DestinationEndpoint
	}
	return ""
}

func init() {
	proto.RegisterType((*DelayedMessage)(nil), "axbolt.delayedmessage.DelayedMessage")
}

func init() {
	proto.RegisterFile("src/axbolt/delayedmessage/delayedmessage.proto", fileDescriptor_delayedmessage_d65a2173b51c3030)
}

var fileDescriptor_delayedmessage_d65a2173b51c3030 = []byte{
	// 185 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0x2b, 0x2e, 0x4a, 0xd6,
	0x4f, 0xac, 0x48, 0xca, 0xcf, 0x29, 0xd1, 0x4f, 0x49, 0xcd, 0x49, 0xac, 0x4c, 0x4d, 0xc9, 0x4d,
	0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0x45, 0xe3, 0xea, 0x15, 0x14, 0xe5, 0x97, 0xe4, 0x0b, 0x89, 0x42,
	0xd4, 0xea, 0xa1, 0x4a, 0x4a, 0x89, 0x42, 0x8c, 0xd1, 0x4f, 0xcd, 0x2b, 0x4b, 0xcd, 0xc9, 0x2f,
	0x80, 0xaa, 0x56, 0x9a, 0xc0, 0xc8, 0xc5, 0xe7, 0x02, 0x51, 0xe9, 0x0b, 0x51, 0x29, 0xa4, 0xcb,
	0xc5, 0xe1, 0x0a, 0x55, 0x24, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x6d, 0x24, 0xa8, 0x97, 0x58, 0xa1,
	0x07, 0x13, 0x0b, 0x00, 0xe9, 0x0b, 0x82, 0x2b, 0x11, 0x92, 0xe1, 0xe2, 0xcc, 0x2f, 0x48, 0x2d,
	0x4a, 0x2c, 0xc9, 0xcc, 0xcf, 0x93, 0x60, 0x57, 0x60, 0xd4, 0x60, 0x0d, 0x42, 0x08, 0x08, 0x19,
	0x72, 0x89, 0xa4, 0xa4, 0x16, 0x97, 0x64, 0xe6, 0x81, 0xb9, 0xf1, 0xa9, 0x79, 0x29, 0x05, 0xf9,
	0x99, 0x79, 0x25, 0x12, 0x1c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0xc2, 0x48, 0x72, 0xae, 0x50, 0x29,
	0x27, 0x81, 0x28, 0x3e, 0x54, 0xb7, 0x27, 0xb1, 0x81, 0xdd, 0x6a, 0x0c, 0x08, 0x00, 0x00, 0xff,
	0xff, 0x05, 0xa9, 0x08, 0xa1, 0x0b, 0x01, 0x00, 0x00,
}
