// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/jmalloc/ax/persistence"
	"sync"
)

var (
	lockCommitterMockCommit   sync.RWMutex
	lockCommitterMockRollback sync.RWMutex
)

// Ensure, that CommitterMock does implement Committer.
// If this is not the case, regenerate this file with moq.
var _ persistence.Committer = &CommitterMock{}

// CommitterMock is a mock implementation of Committer.
//
//     func TestSomethingThatUsesCommitter(t *testing.T) {
//
//         // make and configure a mocked Committer
//         mockedCommitter := &CommitterMock{
//             CommitFunc: func() error {
// 	               panic("mock out the Commit method")
//             },
//             RollbackFunc: func() error {
// 	               panic("mock out the Rollback method")
//             },
//         }
//
//         // use mockedCommitter in code that requires Committer
//         // and then make assertions.
//
//     }
type CommitterMock struct {
	// CommitFunc mocks the Commit method.
	CommitFunc func() error

	// RollbackFunc mocks the Rollback method.
	RollbackFunc func() error

	// calls tracks calls to the methods.
	calls struct {
		// Commit holds details about calls to the Commit method.
		Commit []struct {
		}
		// Rollback holds details about calls to the Rollback method.
		Rollback []struct {
		}
	}
}

// Commit calls CommitFunc.
func (mock *CommitterMock) Commit() error {
	if mock.CommitFunc == nil {
		panic("CommitterMock.CommitFunc: method is nil but Committer.Commit was just called")
	}
	callInfo := struct {
	}{}
	lockCommitterMockCommit.Lock()
	mock.calls.Commit = append(mock.calls.Commit, callInfo)
	lockCommitterMockCommit.Unlock()
	return mock.CommitFunc()
}

// CommitCalls gets all the calls that were made to Commit.
// Check the length with:
//     len(mockedCommitter.CommitCalls())
func (mock *CommitterMock) CommitCalls() []struct {
} {
	var calls []struct {
	}
	lockCommitterMockCommit.RLock()
	calls = mock.calls.Commit
	lockCommitterMockCommit.RUnlock()
	return calls
}

// Rollback calls RollbackFunc.
func (mock *CommitterMock) Rollback() error {
	if mock.RollbackFunc == nil {
		panic("CommitterMock.RollbackFunc: method is nil but Committer.Rollback was just called")
	}
	callInfo := struct {
	}{}
	lockCommitterMockRollback.Lock()
	mock.calls.Rollback = append(mock.calls.Rollback, callInfo)
	lockCommitterMockRollback.Unlock()
	return mock.RollbackFunc()
}

// RollbackCalls gets all the calls that were made to Rollback.
// Check the length with:
//     len(mockedCommitter.RollbackCalls())
func (mock *CommitterMock) RollbackCalls() []struct {
} {
	var calls []struct {
	}
	lockCommitterMockRollback.RLock()
	calls = mock.calls.Rollback
	lockCommitterMockRollback.RUnlock()
	return calls
}

var (
	lockDataStoreMockBeginTx sync.RWMutex
)

// Ensure, that DataStoreMock does implement DataStore.
// If this is not the case, regenerate this file with moq.
var _ persistence.DataStore = &DataStoreMock{}

// DataStoreMock is a mock implementation of DataStore.
//
//     func TestSomethingThatUsesDataStore(t *testing.T) {
//
//         // make and configure a mocked DataStore
//         mockedDataStore := &DataStoreMock{
//             BeginTxFunc: func(ctx context.Context) (persistence.Tx, persistence.Committer, error) {
// 	               panic("mock out the BeginTx method")
//             },
//         }
//
//         // use mockedDataStore in code that requires DataStore
//         // and then make assertions.
//
//     }
type DataStoreMock struct {
	// BeginTxFunc mocks the BeginTx method.
	BeginTxFunc func(ctx context.Context) (persistence.Tx, persistence.Committer, error)

	// calls tracks calls to the methods.
	calls struct {
		// BeginTx holds details about calls to the BeginTx method.
		BeginTx []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
}

// BeginTx calls BeginTxFunc.
func (mock *DataStoreMock) BeginTx(ctx context.Context) (persistence.Tx, persistence.Committer, error) {
	if mock.BeginTxFunc == nil {
		panic("DataStoreMock.BeginTxFunc: method is nil but DataStore.BeginTx was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	lockDataStoreMockBeginTx.Lock()
	mock.calls.BeginTx = append(mock.calls.BeginTx, callInfo)
	lockDataStoreMockBeginTx.Unlock()
	return mock.BeginTxFunc(ctx)
}

// BeginTxCalls gets all the calls that were made to BeginTx.
// Check the length with:
//     len(mockedDataStore.BeginTxCalls())
func (mock *DataStoreMock) BeginTxCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	lockDataStoreMockBeginTx.RLock()
	calls = mock.calls.BeginTx
	lockDataStoreMockBeginTx.RUnlock()
	return calls
}

var (
	lockTxMockDataStore sync.RWMutex
)

// Ensure, that TxMock does implement Tx.
// If this is not the case, regenerate this file with moq.
var _ persistence.Tx = &TxMock{}

// TxMock is a mock implementation of Tx.
//
//     func TestSomethingThatUsesTx(t *testing.T) {
//
//         // make and configure a mocked Tx
//         mockedTx := &TxMock{
//             DataStoreFunc: func() persistence.DataStore {
// 	               panic("mock out the DataStore method")
//             },
//         }
//
//         // use mockedTx in code that requires Tx
//         // and then make assertions.
//
//     }
type TxMock struct {
	// DataStoreFunc mocks the DataStore method.
	DataStoreFunc func() persistence.DataStore

	// calls tracks calls to the methods.
	calls struct {
		// DataStore holds details about calls to the DataStore method.
		DataStore []struct {
		}
	}
}

// DataStore calls DataStoreFunc.
func (mock *TxMock) DataStore() persistence.DataStore {
	if mock.DataStoreFunc == nil {
		panic("TxMock.DataStoreFunc: method is nil but Tx.DataStore was just called")
	}
	callInfo := struct {
	}{}
	lockTxMockDataStore.Lock()
	mock.calls.DataStore = append(mock.calls.DataStore, callInfo)
	lockTxMockDataStore.Unlock()
	return mock.DataStoreFunc()
}

// DataStoreCalls gets all the calls that were made to DataStore.
// Check the length with:
//     len(mockedTx.DataStoreCalls())
func (mock *TxMock) DataStoreCalls() []struct {
} {
	var calls []struct {
	}
	lockTxMockDataStore.RLock()
	calls = mock.calls.DataStore
	lockTxMockDataStore.RUnlock()
	return calls
}
