// Code generated by protoc-gen-go. DO NOT EDIT.
// source: examples/banking/messages/account.proto

package messages

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// OpenAccount is a command that opens a new bank account.
type OpenAccount struct {
	AccountId            string   `protobuf:"bytes,1,opt,name=account_id,json=accountId" json:"account_id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OpenAccount) Reset()         { *m = OpenAccount{} }
func (m *OpenAccount) String() string { return proto.CompactTextString(m) }
func (*OpenAccount) ProtoMessage()    {}
func (*OpenAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_00996e67f678d99a, []int{0}
}
func (m *OpenAccount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpenAccount.Unmarshal(m, b)
}
func (m *OpenAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpenAccount.Marshal(b, m, deterministic)
}
func (dst *OpenAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpenAccount.Merge(dst, src)
}
func (m *OpenAccount) XXX_Size() int {
	return xxx_messageInfo_OpenAccount.Size(m)
}
func (m *OpenAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_OpenAccount.DiscardUnknown(m)
}

var xxx_messageInfo_OpenAccount proto.InternalMessageInfo

func (m *OpenAccount) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *OpenAccount) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// AccountOpened is an event that occurs when a new account is opened.
type AccountOpened struct {
	AccountId            string   `protobuf:"bytes,1,opt,name=account_id,json=accountId" json:"account_id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountOpened) Reset()         { *m = AccountOpened{} }
func (m *AccountOpened) String() string { return proto.CompactTextString(m) }
func (*AccountOpened) ProtoMessage()    {}
func (*AccountOpened) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_00996e67f678d99a, []int{1}
}
func (m *AccountOpened) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountOpened.Unmarshal(m, b)
}
func (m *AccountOpened) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountOpened.Marshal(b, m, deterministic)
}
func (dst *AccountOpened) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountOpened.Merge(dst, src)
}
func (m *AccountOpened) XXX_Size() int {
	return xxx_messageInfo_AccountOpened.Size(m)
}
func (m *AccountOpened) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountOpened.DiscardUnknown(m)
}

var xxx_messageInfo_AccountOpened proto.InternalMessageInfo

func (m *AccountOpened) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *AccountOpened) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*OpenAccount)(nil), "ax.examples.banking.OpenAccount")
	proto.RegisterType((*AccountOpened)(nil), "ax.examples.banking.AccountOpened")
}

func init() {
	proto.RegisterFile("examples/banking/messages/account.proto", fileDescriptor_account_00996e67f678d99a)
}

var fileDescriptor_account_00996e67f678d99a = []byte{
	// 145 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x4f, 0xad, 0x48, 0xcc,
	0x2d, 0xc8, 0x49, 0x2d, 0xd6, 0x4f, 0x4a, 0xcc, 0xcb, 0xce, 0xcc, 0x4b, 0xd7, 0xcf, 0x4d, 0x2d,
	0x2e, 0x4e, 0x4c, 0x4f, 0x2d, 0xd6, 0x4f, 0x4c, 0x4e, 0xce, 0x2f, 0xcd, 0x2b, 0xd1, 0x2b, 0x28,
	0xca, 0x2f, 0xc9, 0x17, 0x12, 0x4e, 0xac, 0xd0, 0x83, 0xa9, 0xd5, 0x83, 0xaa, 0x55, 0x72, 0xe0,
	0xe2, 0xf6, 0x2f, 0x48, 0xcd, 0x73, 0x84, 0xa8, 0x14, 0x92, 0xe5, 0xe2, 0x82, 0x6a, 0x8a, 0xcf,
	0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0xe2, 0x84, 0x8a, 0x78, 0xa6, 0x08, 0x09, 0x71,
	0xb1, 0xe4, 0x25, 0xe6, 0xa6, 0x4a, 0x30, 0x81, 0x25, 0xc0, 0x6c, 0x25, 0x27, 0x2e, 0x5e, 0xa8,
	0x6e, 0x90, 0x41, 0xa9, 0x29, 0x64, 0x98, 0xe1, 0xc4, 0x15, 0xc5, 0x01, 0x73, 0x74, 0x12, 0x1b,
	0xd8, 0xb5, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x5c, 0xa6, 0x2d, 0xb1, 0xd8, 0x00, 0x00,
	0x00,
}
