// Code generated by protoc-gen-go. DO NOT EDIT.
// source: examples/banking/messages/account.proto

package messages

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// OpenAccount is a command that opens a new bank account.
type OpenAccount struct {
	AccountId            string   `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OpenAccount) Reset()         { *m = OpenAccount{} }
func (m *OpenAccount) String() string { return proto.CompactTextString(m) }
func (*OpenAccount) ProtoMessage()    {}
func (*OpenAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_9df08c57b6a370e5, []int{0}
}

func (m *OpenAccount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpenAccount.Unmarshal(m, b)
}
func (m *OpenAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpenAccount.Marshal(b, m, deterministic)
}
func (m *OpenAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpenAccount.Merge(m, src)
}
func (m *OpenAccount) XXX_Size() int {
	return xxx_messageInfo_OpenAccount.Size(m)
}
func (m *OpenAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_OpenAccount.DiscardUnknown(m)
}

var xxx_messageInfo_OpenAccount proto.InternalMessageInfo

func (m *OpenAccount) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *OpenAccount) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// AccountOpened is an event that occurs when a new account is opened.
type AccountOpened struct {
	AccountId            string   `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountOpened) Reset()         { *m = AccountOpened{} }
func (m *AccountOpened) String() string { return proto.CompactTextString(m) }
func (*AccountOpened) ProtoMessage()    {}
func (*AccountOpened) Descriptor() ([]byte, []int) {
	return fileDescriptor_9df08c57b6a370e5, []int{1}
}

func (m *AccountOpened) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountOpened.Unmarshal(m, b)
}
func (m *AccountOpened) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountOpened.Marshal(b, m, deterministic)
}
func (m *AccountOpened) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountOpened.Merge(m, src)
}
func (m *AccountOpened) XXX_Size() int {
	return xxx_messageInfo_AccountOpened.Size(m)
}
func (m *AccountOpened) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountOpened.DiscardUnknown(m)
}

var xxx_messageInfo_AccountOpened proto.InternalMessageInfo

func (m *AccountOpened) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *AccountOpened) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// CreditAccount is a command that credits funds to an account.
type CreditAccount struct {
	AccountId            string   `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	AmountInCents        int32    `protobuf:"varint,2,opt,name=amount_in_cents,json=amountInCents,proto3" json:"amount_in_cents,omitempty"`
	TransferId           string   `protobuf:"bytes,3,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreditAccount) Reset()         { *m = CreditAccount{} }
func (m *CreditAccount) String() string { return proto.CompactTextString(m) }
func (*CreditAccount) ProtoMessage()    {}
func (*CreditAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_9df08c57b6a370e5, []int{2}
}

func (m *CreditAccount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreditAccount.Unmarshal(m, b)
}
func (m *CreditAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreditAccount.Marshal(b, m, deterministic)
}
func (m *CreditAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreditAccount.Merge(m, src)
}
func (m *CreditAccount) XXX_Size() int {
	return xxx_messageInfo_CreditAccount.Size(m)
}
func (m *CreditAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_CreditAccount.DiscardUnknown(m)
}

var xxx_messageInfo_CreditAccount proto.InternalMessageInfo

func (m *CreditAccount) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *CreditAccount) GetAmountInCents() int32 {
	if m != nil {
		return m.AmountInCents
	}
	return 0
}

func (m *CreditAccount) GetTransferId() string {
	if m != nil {
		return m.TransferId
	}
	return ""
}

// AccountCredited is an event that occurs when funds are credited to an
// account.
type AccountCredited struct {
	AccountId            string   `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	AmountInCents        int32    `protobuf:"varint,2,opt,name=amount_in_cents,json=amountInCents,proto3" json:"amount_in_cents,omitempty"`
	TransferId           string   `protobuf:"bytes,3,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountCredited) Reset()         { *m = AccountCredited{} }
func (m *AccountCredited) String() string { return proto.CompactTextString(m) }
func (*AccountCredited) ProtoMessage()    {}
func (*AccountCredited) Descriptor() ([]byte, []int) {
	return fileDescriptor_9df08c57b6a370e5, []int{3}
}

func (m *AccountCredited) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountCredited.Unmarshal(m, b)
}
func (m *AccountCredited) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountCredited.Marshal(b, m, deterministic)
}
func (m *AccountCredited) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountCredited.Merge(m, src)
}
func (m *AccountCredited) XXX_Size() int {
	return xxx_messageInfo_AccountCredited.Size(m)
}
func (m *AccountCredited) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountCredited.DiscardUnknown(m)
}

var xxx_messageInfo_AccountCredited proto.InternalMessageInfo

func (m *AccountCredited) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *AccountCredited) GetAmountInCents() int32 {
	if m != nil {
		return m.AmountInCents
	}
	return 0
}

func (m *AccountCredited) GetTransferId() string {
	if m != nil {
		return m.TransferId
	}
	return ""
}

// DebitAccount is a command that debits funds from an account.
type DebitAccount struct {
	AccountId            string   `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	AmountInCents        int32    `protobuf:"varint,2,opt,name=amount_in_cents,json=amountInCents,proto3" json:"amount_in_cents,omitempty"`
	TransferId           string   `protobuf:"bytes,3,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DebitAccount) Reset()         { *m = DebitAccount{} }
func (m *DebitAccount) String() string { return proto.CompactTextString(m) }
func (*DebitAccount) ProtoMessage()    {}
func (*DebitAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_9df08c57b6a370e5, []int{4}
}

func (m *DebitAccount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DebitAccount.Unmarshal(m, b)
}
func (m *DebitAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DebitAccount.Marshal(b, m, deterministic)
}
func (m *DebitAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DebitAccount.Merge(m, src)
}
func (m *DebitAccount) XXX_Size() int {
	return xxx_messageInfo_DebitAccount.Size(m)
}
func (m *DebitAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_DebitAccount.DiscardUnknown(m)
}

var xxx_messageInfo_DebitAccount proto.InternalMessageInfo

func (m *DebitAccount) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *DebitAccount) GetAmountInCents() int32 {
	if m != nil {
		return m.AmountInCents
	}
	return 0
}

func (m *DebitAccount) GetTransferId() string {
	if m != nil {
		return m.TransferId
	}
	return ""
}

// AccountDebited is an event that occurs when funds are debited from an
// account.
type AccountDebited struct {
	AccountId            string   `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	AmountInCents        int32    `protobuf:"varint,2,opt,name=amount_in_cents,json=amountInCents,proto3" json:"amount_in_cents,omitempty"`
	TransferId           string   `protobuf:"bytes,3,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountDebited) Reset()         { *m = AccountDebited{} }
func (m *AccountDebited) String() string { return proto.CompactTextString(m) }
func (*AccountDebited) ProtoMessage()    {}
func (*AccountDebited) Descriptor() ([]byte, []int) {
	return fileDescriptor_9df08c57b6a370e5, []int{5}
}

func (m *AccountDebited) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountDebited.Unmarshal(m, b)
}
func (m *AccountDebited) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountDebited.Marshal(b, m, deterministic)
}
func (m *AccountDebited) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountDebited.Merge(m, src)
}
func (m *AccountDebited) XXX_Size() int {
	return xxx_messageInfo_AccountDebited.Size(m)
}
func (m *AccountDebited) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountDebited.DiscardUnknown(m)
}

var xxx_messageInfo_AccountDebited proto.InternalMessageInfo

func (m *AccountDebited) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *AccountDebited) GetAmountInCents() int32 {
	if m != nil {
		return m.AmountInCents
	}
	return 0
}

func (m *AccountDebited) GetTransferId() string {
	if m != nil {
		return m.TransferId
	}
	return ""
}

func init() {
	proto.RegisterType((*OpenAccount)(nil), "ax.examples.banking.OpenAccount")
	proto.RegisterType((*AccountOpened)(nil), "ax.examples.banking.AccountOpened")
	proto.RegisterType((*CreditAccount)(nil), "ax.examples.banking.CreditAccount")
	proto.RegisterType((*AccountCredited)(nil), "ax.examples.banking.AccountCredited")
	proto.RegisterType((*DebitAccount)(nil), "ax.examples.banking.DebitAccount")
	proto.RegisterType((*AccountDebited)(nil), "ax.examples.banking.AccountDebited")
}

func init() {
	proto.RegisterFile("examples/banking/messages/account.proto", fileDescriptor_9df08c57b6a370e5)
}

var fileDescriptor_9df08c57b6a370e5 = []byte{
	// 237 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x92, 0x3f, 0x4f, 0x84, 0x40,
	0x10, 0xc5, 0x73, 0xfe, 0x8b, 0x37, 0x27, 0x5e, 0xb2, 0x36, 0xd7, 0x18, 0x0d, 0x85, 0x5a, 0x41,
	0xe1, 0x17, 0x50, 0xb0, 0xa1, 0x32, 0xa1, 0xb4, 0x21, 0x03, 0x3b, 0x12, 0xa2, 0x3b, 0x90, 0xdd,
	0x55, 0xf1, 0xdb, 0x1b, 0x76, 0x97, 0x5a, 0x63, 0x2e, 0x74, 0x93, 0x37, 0x6f, 0xde, 0x6f, 0x26,
	0x19, 0xb8, 0xa5, 0x11, 0xd5, 0xf0, 0x4e, 0x26, 0xad, 0x91, 0xdf, 0x3a, 0x6e, 0x53, 0x45, 0xc6,
	0x60, 0x4b, 0x26, 0xc5, 0xa6, 0xe9, 0x3f, 0xd8, 0x26, 0x83, 0xee, 0x6d, 0x2f, 0x2e, 0x70, 0x4c,
	0x66, 0x6f, 0x12, 0xbc, 0xf1, 0x03, 0x6c, 0x9e, 0x07, 0xe2, 0x47, 0xef, 0x14, 0x97, 0x00, 0x61,
	0xa8, 0xea, 0xe4, 0x6e, 0x75, 0xbd, 0xba, 0x5b, 0x97, 0xeb, 0xa0, 0x14, 0x52, 0x08, 0x38, 0x62,
	0x54, 0xb4, 0x3b, 0x70, 0x0d, 0x57, 0xc7, 0x19, 0x44, 0x61, 0x7a, 0x0a, 0x22, 0xf9, 0x9f, 0x8c,
	0x2f, 0x88, 0x72, 0x4d, 0xb2, 0xb3, 0x7f, 0xdc, 0xe3, 0x06, 0xb6, 0xa8, 0x7c, 0x97, 0xab, 0x86,
	0xd8, 0x1a, 0x17, 0x77, 0x5c, 0x46, 0x5e, 0x2e, 0x38, 0x9f, 0x44, 0x71, 0x05, 0x1b, 0xab, 0x91,
	0xcd, 0x2b, 0xe9, 0x29, 0xe7, 0xd0, 0xe5, 0xc0, 0x2c, 0x15, 0x32, 0xfe, 0x86, 0x6d, 0x40, 0x7a,
	0xfe, 0xef, 0xeb, 0xef, 0x0d, 0xfd, 0x09, 0x67, 0x4f, 0x54, 0x2f, 0x7f, 0xf2, 0x08, 0xe7, 0x01,
	0xe9, 0xf0, 0xcb, 0x5d, 0x9c, 0xc1, 0xcb, 0xe9, 0xfc, 0x9a, 0xf5, 0x89, 0xfb, 0xc9, 0xfb, 0x9f,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xdf, 0x41, 0xe3, 0x00, 0xbe, 0x02, 0x00, 0x00,
}
