// Code generated by protoc-gen-go. DO NOT EDIT.
// source: examples/banking/messages/transfer.proto

package messages

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// StartTransfer is a command that starts a new funds transfer.
type StartTransfer struct {
	TransferId           string   `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	FromAccountId        string   `protobuf:"bytes,2,opt,name=from_account_id,json=fromAccountId,proto3" json:"from_account_id,omitempty"`
	ToAccountId          string   `protobuf:"bytes,3,opt,name=to_account_id,json=toAccountId,proto3" json:"to_account_id,omitempty"`
	AmountInCents        int32    `protobuf:"varint,4,opt,name=amount_in_cents,json=amountInCents,proto3" json:"amount_in_cents,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartTransfer) Reset()         { *m = StartTransfer{} }
func (m *StartTransfer) String() string { return proto.CompactTextString(m) }
func (*StartTransfer) ProtoMessage()    {}
func (*StartTransfer) Descriptor() ([]byte, []int) {
	return fileDescriptor_e75cd10884c5b714, []int{0}
}

func (m *StartTransfer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartTransfer.Unmarshal(m, b)
}
func (m *StartTransfer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartTransfer.Marshal(b, m, deterministic)
}
func (m *StartTransfer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartTransfer.Merge(m, src)
}
func (m *StartTransfer) XXX_Size() int {
	return xxx_messageInfo_StartTransfer.Size(m)
}
func (m *StartTransfer) XXX_DiscardUnknown() {
	xxx_messageInfo_StartTransfer.DiscardUnknown(m)
}

var xxx_messageInfo_StartTransfer proto.InternalMessageInfo

func (m *StartTransfer) GetTransferId() string {
	if m != nil {
		return m.TransferId
	}
	return ""
}

func (m *StartTransfer) GetFromAccountId() string {
	if m != nil {
		return m.FromAccountId
	}
	return ""
}

func (m *StartTransfer) GetToAccountId() string {
	if m != nil {
		return m.ToAccountId
	}
	return ""
}

func (m *StartTransfer) GetAmountInCents() int32 {
	if m != nil {
		return m.AmountInCents
	}
	return 0
}

// TransferStarted is an event that occurs when a funds transfer is started.
type TransferStarted struct {
	TransferId           string   `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	FromAccountId        string   `protobuf:"bytes,2,opt,name=from_account_id,json=fromAccountId,proto3" json:"from_account_id,omitempty"`
	ToAccountId          string   `protobuf:"bytes,3,opt,name=to_account_id,json=toAccountId,proto3" json:"to_account_id,omitempty"`
	AmountInCents        int32    `protobuf:"varint,4,opt,name=amount_in_cents,json=amountInCents,proto3" json:"amount_in_cents,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransferStarted) Reset()         { *m = TransferStarted{} }
func (m *TransferStarted) String() string { return proto.CompactTextString(m) }
func (*TransferStarted) ProtoMessage()    {}
func (*TransferStarted) Descriptor() ([]byte, []int) {
	return fileDescriptor_e75cd10884c5b714, []int{1}
}

func (m *TransferStarted) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransferStarted.Unmarshal(m, b)
}
func (m *TransferStarted) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransferStarted.Marshal(b, m, deterministic)
}
func (m *TransferStarted) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransferStarted.Merge(m, src)
}
func (m *TransferStarted) XXX_Size() int {
	return xxx_messageInfo_TransferStarted.Size(m)
}
func (m *TransferStarted) XXX_DiscardUnknown() {
	xxx_messageInfo_TransferStarted.DiscardUnknown(m)
}

var xxx_messageInfo_TransferStarted proto.InternalMessageInfo

func (m *TransferStarted) GetTransferId() string {
	if m != nil {
		return m.TransferId
	}
	return ""
}

func (m *TransferStarted) GetFromAccountId() string {
	if m != nil {
		return m.FromAccountId
	}
	return ""
}

func (m *TransferStarted) GetToAccountId() string {
	if m != nil {
		return m.ToAccountId
	}
	return ""
}

func (m *TransferStarted) GetAmountInCents() int32 {
	if m != nil {
		return m.AmountInCents
	}
	return 0
}

// MarkTransferComplete is a command that marks a transfer as completed.
type MarkTransferComplete struct {
	TransferId           string   `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MarkTransferComplete) Reset()         { *m = MarkTransferComplete{} }
func (m *MarkTransferComplete) String() string { return proto.CompactTextString(m) }
func (*MarkTransferComplete) ProtoMessage()    {}
func (*MarkTransferComplete) Descriptor() ([]byte, []int) {
	return fileDescriptor_e75cd10884c5b714, []int{2}
}

func (m *MarkTransferComplete) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MarkTransferComplete.Unmarshal(m, b)
}
func (m *MarkTransferComplete) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MarkTransferComplete.Marshal(b, m, deterministic)
}
func (m *MarkTransferComplete) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MarkTransferComplete.Merge(m, src)
}
func (m *MarkTransferComplete) XXX_Size() int {
	return xxx_messageInfo_MarkTransferComplete.Size(m)
}
func (m *MarkTransferComplete) XXX_DiscardUnknown() {
	xxx_messageInfo_MarkTransferComplete.DiscardUnknown(m)
}

var xxx_messageInfo_MarkTransferComplete proto.InternalMessageInfo

func (m *MarkTransferComplete) GetTransferId() string {
	if m != nil {
		return m.TransferId
	}
	return ""
}

// TransferCompleted is an event that occurs when a funds transfer is completed.
type TransferCompleted struct {
	TransferId           string   `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransferCompleted) Reset()         { *m = TransferCompleted{} }
func (m *TransferCompleted) String() string { return proto.CompactTextString(m) }
func (*TransferCompleted) ProtoMessage()    {}
func (*TransferCompleted) Descriptor() ([]byte, []int) {
	return fileDescriptor_e75cd10884c5b714, []int{3}
}

func (m *TransferCompleted) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransferCompleted.Unmarshal(m, b)
}
func (m *TransferCompleted) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransferCompleted.Marshal(b, m, deterministic)
}
func (m *TransferCompleted) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransferCompleted.Merge(m, src)
}
func (m *TransferCompleted) XXX_Size() int {
	return xxx_messageInfo_TransferCompleted.Size(m)
}
func (m *TransferCompleted) XXX_DiscardUnknown() {
	xxx_messageInfo_TransferCompleted.DiscardUnknown(m)
}

var xxx_messageInfo_TransferCompleted proto.InternalMessageInfo

func (m *TransferCompleted) GetTransferId() string {
	if m != nil {
		return m.TransferId
	}
	return ""
}

func init() {
	proto.RegisterType((*StartTransfer)(nil), "ax.examples.banking.StartTransfer")
	proto.RegisterType((*TransferStarted)(nil), "ax.examples.banking.TransferStarted")
	proto.RegisterType((*MarkTransferComplete)(nil), "ax.examples.banking.MarkTransferComplete")
	proto.RegisterType((*TransferCompleted)(nil), "ax.examples.banking.TransferCompleted")
}

func init() {
	proto.RegisterFile("examples/banking/messages/transfer.proto", fileDescriptor_e75cd10884c5b714)
}

var fileDescriptor_e75cd10884c5b714 = []byte{
	// 236 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x91, 0x3d, 0x4f, 0xc3, 0x30,
	0x10, 0x40, 0x65, 0xbe, 0x04, 0x57, 0x45, 0x11, 0x86, 0xa1, 0x1b, 0x95, 0x87, 0x2a, 0x53, 0x32,
	0x80, 0xc4, 0x0c, 0x9d, 0x32, 0xb0, 0x14, 0x26, 0x96, 0xe8, 0x1a, 0x5f, 0xab, 0xaa, 0xd8, 0xae,
	0xec, 0x43, 0xea, 0x0f, 0x42, 0xfc, 0x4e, 0x64, 0xa7, 0x16, 0x88, 0xa5, 0x6b, 0xd7, 0xe7, 0x77,
	0xd2, 0xf3, 0x1d, 0x54, 0xb4, 0x43, 0xb3, 0xfd, 0xa0, 0xd0, 0x2c, 0xd0, 0x6e, 0xd6, 0x76, 0xd5,
	0x18, 0x0a, 0x01, 0x57, 0x14, 0x1a, 0xf6, 0x68, 0xc3, 0x92, 0x7c, 0xbd, 0xf5, 0x8e, 0x9d, 0xbc,
	0xc1, 0x5d, 0x9d, 0xe5, 0x7a, 0x2f, 0xab, 0x2f, 0x01, 0xc5, 0x2b, 0xa3, 0xe7, 0xb7, 0xbd, 0x2c,
	0xef, 0x60, 0x94, 0x07, 0xbb, 0xb5, 0x1e, 0x8b, 0x89, 0xa8, 0xae, 0xe6, 0x90, 0x51, 0xab, 0xe5,
	0x14, 0xca, 0xa5, 0x77, 0xa6, 0xc3, 0xbe, 0x77, 0x9f, 0x96, 0xa3, 0x74, 0x92, 0xa4, 0x22, 0xe2,
	0xa7, 0x81, 0xb6, 0x5a, 0x2a, 0x28, 0xd8, 0xfd, 0xb5, 0x4e, 0x93, 0x35, 0x62, 0xf7, 0xeb, 0x4c,
	0xa1, 0x44, 0x33, 0xbc, 0xdb, 0xae, 0x27, 0xcb, 0x61, 0x7c, 0x36, 0x11, 0xd5, 0xf9, 0xbc, 0x18,
	0x70, 0x6b, 0x67, 0x11, 0xaa, 0x6f, 0x01, 0x65, 0x2e, 0x4c, 0xb9, 0xa4, 0x8f, 0x33, 0xf4, 0x11,
	0x6e, 0x5f, 0xd0, 0x6f, 0x72, 0xeb, 0xcc, 0xc5, 0x75, 0x33, 0x1d, 0x8c, 0x55, 0x0f, 0x70, 0xfd,
	0x7f, 0xe8, 0xf0, 0x17, 0x9f, 0xe1, 0xfd, 0x32, 0x9f, 0x7b, 0x71, 0x91, 0xce, 0x7c, 0xff, 0x13,
	0x00, 0x00, 0xff, 0xff, 0xfb, 0x86, 0xb4, 0xcf, 0x12, 0x02, 0x00, 0x00,
}
