// Code generated by protoc-gen-go. DO NOT EDIT.
// source: src/ax/internal/messagetest/messages.proto

/*
Package messagetest is a generated protocol buffer package.

It is generated from these files:
	src/ax/internal/messagetest/messages.proto
	src/ax/internal/messagetest/nopackage.proto

It has these top-level messages:
	Message
	Command
	Event
	NoPackage
*/
package messagetest

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Message struct {
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Command struct {
}

func (m *Command) Reset()                    { *m = Command{} }
func (m *Command) String() string            { return proto.CompactTextString(m) }
func (*Command) ProtoMessage()               {}
func (*Command) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type Event struct {
}

func (m *Event) Reset()                    { *m = Event{} }
func (m *Event) String() string            { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()               {}
func (*Event) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func init() {
	proto.RegisterType((*Message)(nil), "ax.internal.messagetest.Message")
	proto.RegisterType((*Command)(nil), "ax.internal.messagetest.Command")
	proto.RegisterType((*Event)(nil), "ax.internal.messagetest.Event")
}

func init() { proto.RegisterFile("src/ax/internal/messagetest/messages.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 108 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0x2a, 0x2e, 0x4a, 0xd6,
	0x4f, 0xac, 0xd0, 0xcf, 0xcc, 0x2b, 0x49, 0x2d, 0xca, 0x4b, 0xcc, 0xd1, 0xcf, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0x2d, 0x49, 0x2d, 0x2e, 0x81, 0xb1, 0x8b, 0xf5, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2,
	0x85, 0xc4, 0x13, 0x2b, 0xf4, 0x60, 0xea, 0xf4, 0x90, 0xd4, 0x29, 0x71, 0x72, 0xb1, 0xfb, 0x42,
	0xb8, 0x20, 0xa6, 0x73, 0x7e, 0x6e, 0x6e, 0x62, 0x5e, 0x8a, 0x12, 0x3b, 0x17, 0xab, 0x6b, 0x59,
	0x6a, 0x5e, 0x89, 0x13, 0x6f, 0x14, 0x37, 0x92, 0xea, 0x24, 0x36, 0xb0, 0x69, 0xc6, 0x80, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x07, 0xa6, 0x38, 0x60, 0x7b, 0x00, 0x00, 0x00,
}
