// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: github.com/jmalloc/ax/axtest/testmessages/messages.proto

package testmessages

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// Message is a protocol buffers message that implements ax.Message.
type Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Message) Reset() {
	*x = Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_jmalloc_ax_axtest_testmessages_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_jmalloc_ax_axtest_testmessages_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_github_com_jmalloc_ax_axtest_testmessages_messages_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// MessageA is a protocol buffers message that implements ax.Message.
type MessageA struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *MessageA) Reset() {
	*x = MessageA{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_jmalloc_ax_axtest_testmessages_messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageA) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageA) ProtoMessage() {}

func (x *MessageA) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_jmalloc_ax_axtest_testmessages_messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageA.ProtoReflect.Descriptor instead.
func (*MessageA) Descriptor() ([]byte, []int) {
	return file_github_com_jmalloc_ax_axtest_testmessages_messages_proto_rawDescGZIP(), []int{1}
}

func (x *MessageA) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// MessageB is a protocol buffers message that implements ax.Message.
type MessageB struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *MessageB) Reset() {
	*x = MessageB{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_jmalloc_ax_axtest_testmessages_messages_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageB) ProtoMessage() {}

func (x *MessageB) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_jmalloc_ax_axtest_testmessages_messages_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageB.ProtoReflect.Descriptor instead.
func (*MessageB) Descriptor() ([]byte, []int) {
	return file_github_com_jmalloc_ax_axtest_testmessages_messages_proto_rawDescGZIP(), []int{2}
}

func (x *MessageB) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// MessageC is a protocol buffers message that implements ax.Message.
type MessageC struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *MessageC) Reset() {
	*x = MessageC{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_jmalloc_ax_axtest_testmessages_messages_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageC) ProtoMessage() {}

func (x *MessageC) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_jmalloc_ax_axtest_testmessages_messages_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageC.ProtoReflect.Descriptor instead.
func (*MessageC) Descriptor() ([]byte, []int) {
	return file_github_com_jmalloc_ax_axtest_testmessages_messages_proto_rawDescGZIP(), []int{3}
}

func (x *MessageC) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// MessageD is a protocol buffers message that implements ax.Message.
type MessageD struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *MessageD) Reset() {
	*x = MessageD{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_jmalloc_ax_axtest_testmessages_messages_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageD) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageD) ProtoMessage() {}

func (x *MessageD) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_jmalloc_ax_axtest_testmessages_messages_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageD.ProtoReflect.Descriptor instead.
func (*MessageD) Descriptor() ([]byte, []int) {
	return file_github_com_jmalloc_ax_axtest_testmessages_messages_proto_rawDescGZIP(), []int{4}
}

func (x *MessageD) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// MessageE is a protocol buffers message that implements ax.Message.
type MessageE struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *MessageE) Reset() {
	*x = MessageE{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_jmalloc_ax_axtest_testmessages_messages_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageE) ProtoMessage() {}

func (x *MessageE) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_jmalloc_ax_axtest_testmessages_messages_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageE.ProtoReflect.Descriptor instead.
func (*MessageE) Descriptor() ([]byte, []int) {
	return file_github_com_jmalloc_ax_axtest_testmessages_messages_proto_rawDescGZIP(), []int{5}
}

func (x *MessageE) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// MessageF is a protocol buffers message that implements ax.Message.
type MessageF struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *MessageF) Reset() {
	*x = MessageF{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_jmalloc_ax_axtest_testmessages_messages_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageF) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageF) ProtoMessage() {}

func (x *MessageF) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_jmalloc_ax_axtest_testmessages_messages_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageF.ProtoReflect.Descriptor instead.
func (*MessageF) Descriptor() ([]byte, []int) {
	return file_github_com_jmalloc_ax_axtest_testmessages_messages_proto_rawDescGZIP(), []int{6}
}

func (x *MessageF) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// Command is a protocol buffers message that implements ax.Command.
type Command struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Command) Reset() {
	*x = Command{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_jmalloc_ax_axtest_testmessages_messages_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_jmalloc_ax_axtest_testmessages_messages_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_github_com_jmalloc_ax_axtest_testmessages_messages_proto_rawDescGZIP(), []int{7}
}

func (x *Command) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// SelfValidatingCommand is a protocol buffers message that
// implements both ax.Command and endpoint.SelfValidatingMessage.
type SelfValidatingCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *SelfValidatingCommand) Reset() {
	*x = SelfValidatingCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_jmalloc_ax_axtest_testmessages_messages_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SelfValidatingCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelfValidatingCommand) ProtoMessage() {}

func (x *SelfValidatingCommand) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_jmalloc_ax_axtest_testmessages_messages_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelfValidatingCommand.ProtoReflect.Descriptor instead.
func (*SelfValidatingCommand) Descriptor() ([]byte, []int) {
	return file_github_com_jmalloc_ax_axtest_testmessages_messages_proto_rawDescGZIP(), []int{8}
}

func (x *SelfValidatingCommand) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// FailedSelfValidatingCommand is a protocol buffers message that
// implements both ax.Command and endpoint.SelfValidatingMessage.
// Its Validate method returns validation error to test failure
// scenarios in unit tests
type FailedSelfValidatingCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *FailedSelfValidatingCommand) Reset() {
	*x = FailedSelfValidatingCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_jmalloc_ax_axtest_testmessages_messages_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FailedSelfValidatingCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailedSelfValidatingCommand) ProtoMessage() {}

func (x *FailedSelfValidatingCommand) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_jmalloc_ax_axtest_testmessages_messages_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailedSelfValidatingCommand.ProtoReflect.Descriptor instead.
func (*FailedSelfValidatingCommand) Descriptor() ([]byte, []int) {
	return file_github_com_jmalloc_ax_axtest_testmessages_messages_proto_rawDescGZIP(), []int{9}
}

func (x *FailedSelfValidatingCommand) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// Event is a protocol buffers message that implements ax.Event.
type Event struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Event) Reset() {
	*x = Event{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_jmalloc_ax_axtest_testmessages_messages_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_jmalloc_ax_axtest_testmessages_messages_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_github_com_jmalloc_ax_axtest_testmessages_messages_proto_rawDescGZIP(), []int{10}
}

func (x *Event) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// SelfValidatingEvent is a protocol buffers message that
// implements both ax.Event and endpoint.SelfValidatingMessage.
type SelfValidatingEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *SelfValidatingEvent) Reset() {
	*x = SelfValidatingEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_jmalloc_ax_axtest_testmessages_messages_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SelfValidatingEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelfValidatingEvent) ProtoMessage() {}

func (x *SelfValidatingEvent) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_jmalloc_ax_axtest_testmessages_messages_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelfValidatingEvent.ProtoReflect.Descriptor instead.
func (*SelfValidatingEvent) Descriptor() ([]byte, []int) {
	return file_github_com_jmalloc_ax_axtest_testmessages_messages_proto_rawDescGZIP(), []int{11}
}

func (x *SelfValidatingEvent) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// FailedSelfValidatingEvent is a protocol buffers message that
// implements both ax.Event and endpoint.SelfValidatingMessage.
// Its Validate method returns validation error to test failure
// scenarios in unit tests
type FailedSelfValidatingEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *FailedSelfValidatingEvent) Reset() {
	*x = FailedSelfValidatingEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_jmalloc_ax_axtest_testmessages_messages_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FailedSelfValidatingEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailedSelfValidatingEvent) ProtoMessage() {}

func (x *FailedSelfValidatingEvent) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_jmalloc_ax_axtest_testmessages_messages_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailedSelfValidatingEvent.ProtoReflect.Descriptor instead.
func (*FailedSelfValidatingEvent) Descriptor() ([]byte, []int) {
	return file_github_com_jmalloc_ax_axtest_testmessages_messages_proto_rawDescGZIP(), []int{12}
}

func (x *FailedSelfValidatingEvent) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// NonAxMessage is a protocol buffers message that does not implement ax.Message.
type NonAxMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *NonAxMessage) Reset() {
	*x = NonAxMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_jmalloc_ax_axtest_testmessages_messages_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NonAxMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NonAxMessage) ProtoMessage() {}

func (x *NonAxMessage) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_jmalloc_ax_axtest_testmessages_messages_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NonAxMessage.ProtoReflect.Descriptor instead.
func (*NonAxMessage) Descriptor() ([]byte, []int) {
	return file_github_com_jmalloc_ax_axtest_testmessages_messages_proto_rawDescGZIP(), []int{13}
}

func (x *NonAxMessage) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_github_com_jmalloc_ax_axtest_testmessages_messages_proto protoreflect.FileDescriptor

var file_github_com_jmalloc_ax_axtest_testmessages_messages_proto_rawDesc = []byte{
	0x0a, 0x38, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6a, 0x6d, 0x61,
	0x6c, 0x6c, 0x6f, 0x63, 0x2f, 0x61, 0x78, 0x2f, 0x61, 0x78, 0x74, 0x65, 0x73, 0x74, 0x2f, 0x74,
	0x65, 0x73, 0x74, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2f, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x61, 0x78, 0x74, 0x65,
	0x73, 0x74, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x22,
	0x1f, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x22, 0x20, 0x0a, 0x08, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x41, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x22, 0x20, 0x0a, 0x08, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x42, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x22, 0x20, 0x0a, 0x08, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x43,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x20, 0x0a, 0x08, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x20, 0x0a, 0x08, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x45, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x20, 0x0a, 0x08, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x46, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x1f, 0x0a, 0x07,
	0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x2d, 0x0a,
	0x15, 0x53, 0x65, 0x6c, 0x66, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x43,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x33, 0x0a, 0x1b,
	0x46, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x53, 0x65, 0x6c, 0x66, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61,
	0x74, 0x69, 0x6e, 0x67, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x22, 0x1d, 0x0a, 0x05, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x22, 0x2b, 0x0a, 0x13, 0x53, 0x65, 0x6c, 0x66, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69,
	0x6e, 0x67, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x31, 0x0a,
	0x19, 0x46, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x53, 0x65, 0x6c, 0x66, 0x56, 0x61, 0x6c, 0x69, 0x64,
	0x61, 0x74, 0x69, 0x6e, 0x67, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x22, 0x24, 0x0a, 0x0c, 0x4e, 0x6f, 0x6e, 0x41, 0x78, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x2b, 0x5a, 0x29, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6a, 0x6d, 0x61, 0x6c, 0x6c, 0x6f, 0x63, 0x2f, 0x61, 0x78, 0x2f,
	0x61, 0x78, 0x74, 0x65, 0x73, 0x74, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_github_com_jmalloc_ax_axtest_testmessages_messages_proto_rawDescOnce sync.Once
	file_github_com_jmalloc_ax_axtest_testmessages_messages_proto_rawDescData = file_github_com_jmalloc_ax_axtest_testmessages_messages_proto_rawDesc
)

func file_github_com_jmalloc_ax_axtest_testmessages_messages_proto_rawDescGZIP() []byte {
	file_github_com_jmalloc_ax_axtest_testmessages_messages_proto_rawDescOnce.Do(func() {
		file_github_com_jmalloc_ax_axtest_testmessages_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_github_com_jmalloc_ax_axtest_testmessages_messages_proto_rawDescData)
	})
	return file_github_com_jmalloc_ax_axtest_testmessages_messages_proto_rawDescData
}

var file_github_com_jmalloc_ax_axtest_testmessages_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_github_com_jmalloc_ax_axtest_testmessages_messages_proto_goTypes = []interface{}{
	(*Message)(nil),                     // 0: axtest.testmessages.Message
	(*MessageA)(nil),                    // 1: axtest.testmessages.MessageA
	(*MessageB)(nil),                    // 2: axtest.testmessages.MessageB
	(*MessageC)(nil),                    // 3: axtest.testmessages.MessageC
	(*MessageD)(nil),                    // 4: axtest.testmessages.MessageD
	(*MessageE)(nil),                    // 5: axtest.testmessages.MessageE
	(*MessageF)(nil),                    // 6: axtest.testmessages.MessageF
	(*Command)(nil),                     // 7: axtest.testmessages.Command
	(*SelfValidatingCommand)(nil),       // 8: axtest.testmessages.SelfValidatingCommand
	(*FailedSelfValidatingCommand)(nil), // 9: axtest.testmessages.FailedSelfValidatingCommand
	(*Event)(nil),                       // 10: axtest.testmessages.Event
	(*SelfValidatingEvent)(nil),         // 11: axtest.testmessages.SelfValidatingEvent
	(*FailedSelfValidatingEvent)(nil),   // 12: axtest.testmessages.FailedSelfValidatingEvent
	(*NonAxMessage)(nil),                // 13: axtest.testmessages.NonAxMessage
}
var file_github_com_jmalloc_ax_axtest_testmessages_messages_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_github_com_jmalloc_ax_axtest_testmessages_messages_proto_init() }
func file_github_com_jmalloc_ax_axtest_testmessages_messages_proto_init() {
	if File_github_com_jmalloc_ax_axtest_testmessages_messages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_github_com_jmalloc_ax_axtest_testmessages_messages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_jmalloc_ax_axtest_testmessages_messages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageA); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_jmalloc_ax_axtest_testmessages_messages_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageB); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_jmalloc_ax_axtest_testmessages_messages_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageC); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_jmalloc_ax_axtest_testmessages_messages_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageD); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_jmalloc_ax_axtest_testmessages_messages_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageE); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_jmalloc_ax_axtest_testmessages_messages_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageF); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_jmalloc_ax_axtest_testmessages_messages_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Command); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_jmalloc_ax_axtest_testmessages_messages_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SelfValidatingCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_jmalloc_ax_axtest_testmessages_messages_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FailedSelfValidatingCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_jmalloc_ax_axtest_testmessages_messages_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Event); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_jmalloc_ax_axtest_testmessages_messages_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SelfValidatingEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_jmalloc_ax_axtest_testmessages_messages_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FailedSelfValidatingEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_jmalloc_ax_axtest_testmessages_messages_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NonAxMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_github_com_jmalloc_ax_axtest_testmessages_messages_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_jmalloc_ax_axtest_testmessages_messages_proto_goTypes,
		DependencyIndexes: file_github_com_jmalloc_ax_axtest_testmessages_messages_proto_depIdxs,
		MessageInfos:      file_github_com_jmalloc_ax_axtest_testmessages_messages_proto_msgTypes,
	}.Build()
	File_github_com_jmalloc_ax_axtest_testmessages_messages_proto = out.File
	file_github_com_jmalloc_ax_axtest_testmessages_messages_proto_rawDesc = nil
	file_github_com_jmalloc_ax_axtest_testmessages_messages_proto_goTypes = nil
	file_github_com_jmalloc_ax_axtest_testmessages_messages_proto_depIdxs = nil
}
