// Code generated by protoc-gen-go. DO NOT EDIT.
// source: examples/banking/domain/data.proto

package domain

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Account contains data for the account aggregate.
type Account struct {
	AccountId            string   `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	IsOpen               bool     `protobuf:"varint,2,opt,name=is_open,json=isOpen,proto3" json:"is_open,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	BalanceInCents       int32    `protobuf:"varint,4,opt,name=balance_in_cents,json=balanceInCents,proto3" json:"balance_in_cents,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7fadce38753b8e1, []int{0}
}

func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (m *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(m, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *Account) GetIsOpen() bool {
	if m != nil {
		return m.IsOpen
	}
	return false
}

func (m *Account) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Account) GetBalanceInCents() int32 {
	if m != nil {
		return m.BalanceInCents
	}
	return 0
}

// Transfer contains data for the transfer aggregate.
type Transfer struct {
	TransferId           string   `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	FromAccountId        string   `protobuf:"bytes,2,opt,name=from_account_id,json=fromAccountId,proto3" json:"from_account_id,omitempty"`
	ToAccountId          string   `protobuf:"bytes,3,opt,name=to_account_id,json=toAccountId,proto3" json:"to_account_id,omitempty"`
	AmountInCents        int32    `protobuf:"varint,4,opt,name=amount_in_cents,json=amountInCents,proto3" json:"amount_in_cents,omitempty"`
	IsApproved           bool     `protobuf:"varint,5,opt,name=is_approved,json=isApproved,proto3" json:"is_approved,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Transfer) Reset()         { *m = Transfer{} }
func (m *Transfer) String() string { return proto.CompactTextString(m) }
func (*Transfer) ProtoMessage()    {}
func (*Transfer) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7fadce38753b8e1, []int{1}
}

func (m *Transfer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transfer.Unmarshal(m, b)
}
func (m *Transfer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transfer.Marshal(b, m, deterministic)
}
func (m *Transfer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transfer.Merge(m, src)
}
func (m *Transfer) XXX_Size() int {
	return xxx_messageInfo_Transfer.Size(m)
}
func (m *Transfer) XXX_DiscardUnknown() {
	xxx_messageInfo_Transfer.DiscardUnknown(m)
}

var xxx_messageInfo_Transfer proto.InternalMessageInfo

func (m *Transfer) GetTransferId() string {
	if m != nil {
		return m.TransferId
	}
	return ""
}

func (m *Transfer) GetFromAccountId() string {
	if m != nil {
		return m.FromAccountId
	}
	return ""
}

func (m *Transfer) GetToAccountId() string {
	if m != nil {
		return m.ToAccountId
	}
	return ""
}

func (m *Transfer) GetAmountInCents() int32 {
	if m != nil {
		return m.AmountInCents
	}
	return 0
}

func (m *Transfer) GetIsApproved() bool {
	if m != nil {
		return m.IsApproved
	}
	return false
}

func init() {
	proto.RegisterType((*Account)(nil), "ax.examples.banking.Account")
	proto.RegisterType((*Transfer)(nil), "ax.examples.banking.Transfer")
}

func init() { proto.RegisterFile("examples/banking/domain/data.proto", fileDescriptor_a7fadce38753b8e1) }

var fileDescriptor_a7fadce38753b8e1 = []byte{
	// 270 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xbd, 0x4e, 0xc3, 0x30,
	0x14, 0x46, 0x95, 0xd2, 0x9f, 0xf4, 0x56, 0xa1, 0xc8, 0x0c, 0x64, 0x41, 0x44, 0x19, 0xaa, 0x4c,
	0xc9, 0xc0, 0x13, 0x04, 0xa6, 0x4c, 0x48, 0x11, 0x13, 0x8b, 0x75, 0x13, 0xbb, 0xc8, 0xa2, 0xb9,
	0xb6, 0x62, 0x83, 0xba, 0xf1, 0x6a, 0x3c, 0x1a, 0x4a, 0xe2, 0xd2, 0xb2, 0x7d, 0x3a, 0x39, 0x91,
	0x8e, 0x2f, 0xa4, 0xf2, 0x88, 0x9d, 0x39, 0x48, 0x5b, 0x34, 0x48, 0x1f, 0x8a, 0xde, 0x0b, 0xa1,
	0x3b, 0x54, 0x54, 0x08, 0x74, 0x98, 0x9b, 0x5e, 0x3b, 0xcd, 0x6e, 0xf1, 0x98, 0x9f, 0xb4, 0xdc,
	0x6b, 0xe9, 0x37, 0xac, 0xca, 0xb6, 0xd5, 0x9f, 0xe4, 0xd8, 0x3d, 0x00, 0x4e, 0x93, 0x2b, 0x11,
	0x07, 0x49, 0x90, 0xad, 0xeb, 0xb5, 0x27, 0x95, 0x60, 0x77, 0xb0, 0x52, 0x96, 0x6b, 0x23, 0x29,
	0x9e, 0x25, 0x41, 0x16, 0xd6, 0x4b, 0x65, 0x5f, 0x8c, 0x24, 0xc6, 0x60, 0x4e, 0xd8, 0xc9, 0xf8,
	0x6a, 0xfc, 0x63, 0xdc, 0x2c, 0x83, 0x9b, 0x06, 0x0f, 0x48, 0xad, 0xe4, 0x8a, 0x78, 0x2b, 0xc9,
	0xd9, 0x78, 0x9e, 0x04, 0xd9, 0xa2, 0xbe, 0xf6, 0xbc, 0xa2, 0xe7, 0x81, 0xa6, 0x3f, 0x01, 0x84,
	0xaf, 0x3d, 0x92, 0xdd, 0xcb, 0x9e, 0x3d, 0xc0, 0xc6, 0xf9, 0x7d, 0x6e, 0x80, 0x13, 0xaa, 0x04,
	0xdb, 0xc1, 0x76, 0xdf, 0xeb, 0x8e, 0x5f, 0x84, 0xce, 0x46, 0x29, 0x1a, 0x70, 0xf9, 0x17, 0x9b,
	0x42, 0xe4, 0xf4, 0xa5, 0x35, 0xc5, 0x6d, 0x9c, 0x3e, 0x3b, 0x3b, 0xd8, 0x62, 0x37, 0x7d, 0xff,
	0x9f, 0x18, 0x4d, 0xd8, 0x17, 0x0e, 0x51, 0xca, 0x72, 0x34, 0xa6, 0xd7, 0x5f, 0x52, 0xc4, 0x8b,
	0xf1, 0xf1, 0xa0, 0x6c, 0xe9, 0xc9, 0x53, 0xf8, 0xb6, 0x9c, 0xae, 0xdd, 0x2c, 0xc7, 0x4b, 0x3f,
	0xfe, 0x06, 0x00, 0x00, 0xff, 0xff, 0xf9, 0x3a, 0xdb, 0xb3, 0x8f, 0x01, 0x00, 0x00,
}
