// Code generated by moq; DO NOT EDIT
// github.com/matryer/moq

package bustest

import (
	"context"
	"github.com/jmalloc/ax/src/ax/bus"
	"sync"
)

var (
	lockInboundPipelineMockDeliverMessage sync.RWMutex
	lockInboundPipelineMockInitialize     sync.RWMutex
)

// InboundPipelineMock is a mock implementation of InboundPipeline.
//
//     func TestSomethingThatUsesInboundPipeline(t *testing.T) {
//
//         // make and configure a mocked InboundPipeline
//         mockedInboundPipeline := &InboundPipelineMock{
//             DeliverMessageFunc: func(ctx context.Context, s bus.MessageSender, m bus.InboundEnvelope) error {
// 	               panic("TODO: mock out the DeliverMessage method")
//             },
//             InitializeFunc: func(ctx context.Context, t bus.Transport) error {
// 	               panic("TODO: mock out the Initialize method")
//             },
//         }
//
//         // TODO: use mockedInboundPipeline in code that requires InboundPipeline
//         //       and then make assertions.
//
//     }
type InboundPipelineMock struct {
	// DeliverMessageFunc mocks the DeliverMessage method.
	DeliverMessageFunc func(ctx context.Context, s bus.MessageSender, m bus.InboundEnvelope) error

	// InitializeFunc mocks the Initialize method.
	InitializeFunc func(ctx context.Context, t bus.Transport) error

	// calls tracks calls to the methods.
	calls struct {
		// DeliverMessage holds details about calls to the DeliverMessage method.
		DeliverMessage []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// S is the s argument value.
			S bus.MessageSender
			// M is the m argument value.
			M bus.InboundEnvelope
		}
		// Initialize holds details about calls to the Initialize method.
		Initialize []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// T is the t argument value.
			T bus.Transport
		}
	}
}

// DeliverMessage calls DeliverMessageFunc.
func (mock *InboundPipelineMock) DeliverMessage(ctx context.Context, s bus.MessageSender, m bus.InboundEnvelope) error {
	if mock.DeliverMessageFunc == nil {
		panic("moq: InboundPipelineMock.DeliverMessageFunc is nil but InboundPipeline.DeliverMessage was just called")
	}
	callInfo := struct {
		Ctx context.Context
		S   bus.MessageSender
		M   bus.InboundEnvelope
	}{
		Ctx: ctx,
		S:   s,
		M:   m,
	}
	lockInboundPipelineMockDeliverMessage.Lock()
	mock.calls.DeliverMessage = append(mock.calls.DeliverMessage, callInfo)
	lockInboundPipelineMockDeliverMessage.Unlock()
	return mock.DeliverMessageFunc(ctx, s, m)
}

// DeliverMessageCalls gets all the calls that were made to DeliverMessage.
// Check the length with:
//     len(mockedInboundPipeline.DeliverMessageCalls())
func (mock *InboundPipelineMock) DeliverMessageCalls() []struct {
	Ctx context.Context
	S   bus.MessageSender
	M   bus.InboundEnvelope
} {
	var calls []struct {
		Ctx context.Context
		S   bus.MessageSender
		M   bus.InboundEnvelope
	}
	lockInboundPipelineMockDeliverMessage.RLock()
	calls = mock.calls.DeliverMessage
	lockInboundPipelineMockDeliverMessage.RUnlock()
	return calls
}

// Initialize calls InitializeFunc.
func (mock *InboundPipelineMock) Initialize(ctx context.Context, t bus.Transport) error {
	if mock.InitializeFunc == nil {
		panic("moq: InboundPipelineMock.InitializeFunc is nil but InboundPipeline.Initialize was just called")
	}
	callInfo := struct {
		Ctx context.Context
		T   bus.Transport
	}{
		Ctx: ctx,
		T:   t,
	}
	lockInboundPipelineMockInitialize.Lock()
	mock.calls.Initialize = append(mock.calls.Initialize, callInfo)
	lockInboundPipelineMockInitialize.Unlock()
	return mock.InitializeFunc(ctx, t)
}

// InitializeCalls gets all the calls that were made to Initialize.
// Check the length with:
//     len(mockedInboundPipeline.InitializeCalls())
func (mock *InboundPipelineMock) InitializeCalls() []struct {
	Ctx context.Context
	T   bus.Transport
} {
	var calls []struct {
		Ctx context.Context
		T   bus.Transport
	}
	lockInboundPipelineMockInitialize.RLock()
	calls = mock.calls.Initialize
	lockInboundPipelineMockInitialize.RUnlock()
	return calls
}

var (
	lockOutboundPipelineMockInitialize  sync.RWMutex
	lockOutboundPipelineMockSendMessage sync.RWMutex
)

// OutboundPipelineMock is a mock implementation of OutboundPipeline.
//
//     func TestSomethingThatUsesOutboundPipeline(t *testing.T) {
//
//         // make and configure a mocked OutboundPipeline
//         mockedOutboundPipeline := &OutboundPipelineMock{
//             InitializeFunc: func(ctx context.Context, t bus.Transport) error {
// 	               panic("TODO: mock out the Initialize method")
//             },
//             SendMessageFunc: func(ctx context.Context, m bus.OutboundEnvelope) error {
// 	               panic("TODO: mock out the SendMessage method")
//             },
//         }
//
//         // TODO: use mockedOutboundPipeline in code that requires OutboundPipeline
//         //       and then make assertions.
//
//     }
type OutboundPipelineMock struct {
	// InitializeFunc mocks the Initialize method.
	InitializeFunc func(ctx context.Context, t bus.Transport) error

	// SendMessageFunc mocks the SendMessage method.
	SendMessageFunc func(ctx context.Context, m bus.OutboundEnvelope) error

	// calls tracks calls to the methods.
	calls struct {
		// Initialize holds details about calls to the Initialize method.
		Initialize []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// T is the t argument value.
			T bus.Transport
		}
		// SendMessage holds details about calls to the SendMessage method.
		SendMessage []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// M is the m argument value.
			M bus.OutboundEnvelope
		}
	}
}

// Initialize calls InitializeFunc.
func (mock *OutboundPipelineMock) Initialize(ctx context.Context, t bus.Transport) error {
	if mock.InitializeFunc == nil {
		panic("moq: OutboundPipelineMock.InitializeFunc is nil but OutboundPipeline.Initialize was just called")
	}
	callInfo := struct {
		Ctx context.Context
		T   bus.Transport
	}{
		Ctx: ctx,
		T:   t,
	}
	lockOutboundPipelineMockInitialize.Lock()
	mock.calls.Initialize = append(mock.calls.Initialize, callInfo)
	lockOutboundPipelineMockInitialize.Unlock()
	return mock.InitializeFunc(ctx, t)
}

// InitializeCalls gets all the calls that were made to Initialize.
// Check the length with:
//     len(mockedOutboundPipeline.InitializeCalls())
func (mock *OutboundPipelineMock) InitializeCalls() []struct {
	Ctx context.Context
	T   bus.Transport
} {
	var calls []struct {
		Ctx context.Context
		T   bus.Transport
	}
	lockOutboundPipelineMockInitialize.RLock()
	calls = mock.calls.Initialize
	lockOutboundPipelineMockInitialize.RUnlock()
	return calls
}

// SendMessage calls SendMessageFunc.
func (mock *OutboundPipelineMock) SendMessage(ctx context.Context, m bus.OutboundEnvelope) error {
	if mock.SendMessageFunc == nil {
		panic("moq: OutboundPipelineMock.SendMessageFunc is nil but OutboundPipeline.SendMessage was just called")
	}
	callInfo := struct {
		Ctx context.Context
		M   bus.OutboundEnvelope
	}{
		Ctx: ctx,
		M:   m,
	}
	lockOutboundPipelineMockSendMessage.Lock()
	mock.calls.SendMessage = append(mock.calls.SendMessage, callInfo)
	lockOutboundPipelineMockSendMessage.Unlock()
	return mock.SendMessageFunc(ctx, m)
}

// SendMessageCalls gets all the calls that were made to SendMessage.
// Check the length with:
//     len(mockedOutboundPipeline.SendMessageCalls())
func (mock *OutboundPipelineMock) SendMessageCalls() []struct {
	Ctx context.Context
	M   bus.OutboundEnvelope
} {
	var calls []struct {
		Ctx context.Context
		M   bus.OutboundEnvelope
	}
	lockOutboundPipelineMockSendMessage.RLock()
	calls = mock.calls.SendMessage
	lockOutboundPipelineMockSendMessage.RUnlock()
	return calls
}
