// Code generated by protoc-gen-go. DO NOT EDIT.
// source: src/axbolt/outbox/outboxmsg.proto

package outbox

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import ax "github.com/jmalloc/ax/src/ax"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// OutboxMessage is a container for holding outbox message-specific data that is
// serialized into the protobuf format before being persisted in a Bolt bucket
type OutboxMessage struct {
	Envelope             *ax.EnvelopeProto `protobuf:"bytes,1,opt,name=Envelope,proto3" json:"Envelope,omitempty"`
	Operation            int32             `protobuf:"varint,2,opt,name=operation,proto3" json:"operation,omitempty"`
	DestinationEndpoint  string            `protobuf:"bytes,3,opt,name=destination_endpoint,json=destinationEndpoint,proto3" json:"destination_endpoint,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *OutboxMessage) Reset()         { *m = OutboxMessage{} }
func (m *OutboxMessage) String() string { return proto.CompactTextString(m) }
func (*OutboxMessage) ProtoMessage()    {}
func (*OutboxMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_outboxmsg_788d780269e2831f, []int{0}
}
func (m *OutboxMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OutboxMessage.Unmarshal(m, b)
}
func (m *OutboxMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OutboxMessage.Marshal(b, m, deterministic)
}
func (dst *OutboxMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OutboxMessage.Merge(dst, src)
}
func (m *OutboxMessage) XXX_Size() int {
	return xxx_messageInfo_OutboxMessage.Size(m)
}
func (m *OutboxMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_OutboxMessage.DiscardUnknown(m)
}

var xxx_messageInfo_OutboxMessage proto.InternalMessageInfo

func (m *OutboxMessage) GetEnvelope() *ax.EnvelopeProto {
	if m != nil {
		return m.Envelope
	}
	return nil
}

func (m *OutboxMessage) GetOperation() int32 {
	if m != nil {
		return m.Operation
	}
	return 0
}

func (m *OutboxMessage) GetDestinationEndpoint() string {
	if m != nil {
		return m.DestinationEndpoint
	}
	return ""
}

func init() {
	proto.RegisterType((*OutboxMessage)(nil), "axbolt.outbox.OutboxMessage")
}

func init() {
	proto.RegisterFile("src/axbolt/outbox/outboxmsg.proto", fileDescriptor_outboxmsg_788d780269e2831f)
}

var fileDescriptor_outboxmsg_788d780269e2831f = []byte{
	// 184 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x2c, 0x2e, 0x4a, 0xd6,
	0x4f, 0xac, 0x48, 0xca, 0xcf, 0x29, 0xd1, 0xcf, 0x2f, 0x2d, 0x49, 0xca, 0xaf, 0x80, 0x52, 0xb9,
	0xc5, 0xe9, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0xbc, 0x10, 0x69, 0x3d, 0x88, 0xb8, 0x94,
	0x28, 0x44, 0x87, 0x7e, 0x6a, 0x5e, 0x59, 0x6a, 0x4e, 0x7e, 0x41, 0x2a, 0x44, 0x95, 0x52, 0x3f,
	0x23, 0x17, 0xaf, 0x3f, 0x58, 0x85, 0x6f, 0x6a, 0x71, 0x71, 0x62, 0x7a, 0xaa, 0x90, 0x2e, 0x17,
	0x87, 0x2b, 0x54, 0x8d, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0xb7, 0x91, 0xa0, 0x5e, 0x62, 0x85, 0x1e,
	0x4c, 0x2c, 0x00, 0xa4, 0x2d, 0x08, 0xae, 0x44, 0x48, 0x86, 0x8b, 0x33, 0xbf, 0x20, 0xb5, 0x28,
	0xb1, 0x24, 0x33, 0x3f, 0x4f, 0x82, 0x49, 0x81, 0x51, 0x83, 0x35, 0x08, 0x21, 0x20, 0x64, 0xc8,
	0x25, 0x92, 0x92, 0x5a, 0x5c, 0x92, 0x99, 0x07, 0xe6, 0xc6, 0xa7, 0xe6, 0xa5, 0x14, 0xe4, 0x67,
	0xe6, 0x95, 0x48, 0x30, 0x2b, 0x30, 0x6a, 0x70, 0x06, 0x09, 0x23, 0xc9, 0xb9, 0x42, 0xa5, 0x9c,
	0x38, 0xa2, 0xd8, 0x20, 0x4e, 0x4e, 0x62, 0x03, 0x3b, 0xd1, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff,
	0x0a, 0xdd, 0x4c, 0x4b, 0xed, 0x00, 0x00, 0x00,
}
