// Code generated by protoc-gen-go. DO NOT EDIT.
// source: src/axbolt/outbox/outboxmsg.proto

package outbox

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import any "github.com/golang/protobuf/ptypes/any"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// OutboxMessage is a container for holding outbox message-specific data that is
// serialized into the protobuf format before being persisted in a Bolt bucket
type OutboxMessage struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CausationId          string   `protobuf:"bytes,2,opt,name=causation_id,json=causationId,proto3" json:"causation_id,omitempty"`
	CorrelationId        string   `protobuf:"bytes,3,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	CreatedAt            string   `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	SendAt               string   `protobuf:"bytes,5,opt,name=send_at,json=sendAt,proto3" json:"send_at,omitempty"`
	Message              *any.Any `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	Operation            int32    `protobuf:"varint,7,opt,name=operation,proto3" json:"operation,omitempty"`
	DestinationEndpoint  string   `protobuf:"bytes,8,opt,name=destination_endpoint,json=destinationEndpoint,proto3" json:"destination_endpoint,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OutboxMessage) Reset()         { *m = OutboxMessage{} }
func (m *OutboxMessage) String() string { return proto.CompactTextString(m) }
func (*OutboxMessage) ProtoMessage()    {}
func (*OutboxMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_outboxmsg_b21d1230c7af1d6e, []int{0}
}
func (m *OutboxMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OutboxMessage.Unmarshal(m, b)
}
func (m *OutboxMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OutboxMessage.Marshal(b, m, deterministic)
}
func (dst *OutboxMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OutboxMessage.Merge(dst, src)
}
func (m *OutboxMessage) XXX_Size() int {
	return xxx_messageInfo_OutboxMessage.Size(m)
}
func (m *OutboxMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_OutboxMessage.DiscardUnknown(m)
}

var xxx_messageInfo_OutboxMessage proto.InternalMessageInfo

func (m *OutboxMessage) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *OutboxMessage) GetCausationId() string {
	if m != nil {
		return m.CausationId
	}
	return ""
}

func (m *OutboxMessage) GetCorrelationId() string {
	if m != nil {
		return m.CorrelationId
	}
	return ""
}

func (m *OutboxMessage) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *OutboxMessage) GetSendAt() string {
	if m != nil {
		return m.SendAt
	}
	return ""
}

func (m *OutboxMessage) GetMessage() *any.Any {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *OutboxMessage) GetOperation() int32 {
	if m != nil {
		return m.Operation
	}
	return 0
}

func (m *OutboxMessage) GetDestinationEndpoint() string {
	if m != nil {
		return m.DestinationEndpoint
	}
	return ""
}

func init() {
	proto.RegisterType((*OutboxMessage)(nil), "axbolt.outbox.OutboxMessage")
}

func init() {
	proto.RegisterFile("src/axbolt/outbox/outboxmsg.proto", fileDescriptor_outboxmsg_b21d1230c7af1d6e)
}

var fileDescriptor_outboxmsg_b21d1230c7af1d6e = []byte{
	// 271 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0x41, 0x4b, 0xc3, 0x30,
	0x14, 0xc7, 0x69, 0x75, 0xdd, 0xf6, 0x66, 0x77, 0x88, 0x03, 0xa3, 0x28, 0x74, 0x82, 0xd0, 0x53,
	0x8a, 0xfa, 0x09, 0x2a, 0x78, 0xd8, 0x41, 0x84, 0x1e, 0xbd, 0x8c, 0xb4, 0x89, 0x25, 0xd0, 0xe5,
	0x95, 0x24, 0x85, 0xed, 0xeb, 0xf8, 0x49, 0xc5, 0xa4, 0x9b, 0x3b, 0x85, 0xfc, 0x7f, 0x3f, 0xf8,
	0xbf, 0xf7, 0x60, 0x6d, 0x4d, 0x53, 0xf0, 0x7d, 0x8d, 0x9d, 0x2b, 0x70, 0x70, 0x35, 0xee, 0xc7,
	0x67, 0x67, 0x5b, 0xd6, 0x1b, 0x74, 0x48, 0xd2, 0x80, 0x59, 0xc8, 0xef, 0x6e, 0x5b, 0xc4, 0xb6,
	0x93, 0x85, 0x87, 0xf5, 0xf0, 0x5d, 0x70, 0x7d, 0x08, 0xe6, 0xe3, 0x4f, 0x0c, 0xe9, 0xa7, 0xb7,
	0x3e, 0xa4, 0xb5, 0xbc, 0x95, 0x64, 0x09, 0xb1, 0x12, 0x34, 0xca, 0xa2, 0x7c, 0x5e, 0xc5, 0x4a,
	0x90, 0x35, 0x5c, 0x35, 0x7c, 0xb0, 0xdc, 0x29, 0xd4, 0x5b, 0x25, 0x68, 0xec, 0xc9, 0xe2, 0x94,
	0x6d, 0x04, 0x79, 0x82, 0x65, 0x83, 0xc6, 0xc8, 0xee, 0x24, 0x5d, 0x78, 0x29, 0x3d, 0x4b, 0x37,
	0x82, 0x3c, 0x00, 0x34, 0x46, 0x72, 0x27, 0xc5, 0x96, 0x3b, 0x7a, 0xe9, 0x95, 0xf9, 0x98, 0x94,
	0x8e, 0xdc, 0xc0, 0xd4, 0x4a, 0xed, 0xd9, 0xc4, 0xb3, 0xe4, 0xef, 0x5b, 0x3a, 0xc2, 0x60, 0xba,
	0x0b, 0xc3, 0xd1, 0x24, 0x8b, 0xf2, 0xc5, 0xcb, 0x8a, 0x85, 0x85, 0xd8, 0x71, 0x21, 0x56, 0xea,
	0x43, 0x75, 0x94, 0xc8, 0x3d, 0xcc, 0xb1, 0x97, 0xc6, 0xd7, 0xd2, 0x69, 0x16, 0xe5, 0x93, 0xea,
	0x3f, 0x20, 0xcf, 0xb0, 0x12, 0xd2, 0x3a, 0xa5, 0xc3, 0xb0, 0x52, 0x8b, 0x1e, 0x95, 0x76, 0x74,
	0xe6, 0x3b, 0xaf, 0xcf, 0xd8, 0xfb, 0x88, 0xde, 0x66, 0x5f, 0x49, 0xb8, 0x64, 0x9d, 0xf8, 0xc6,
	0xd7, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb3, 0x88, 0x67, 0x8a, 0x84, 0x01, 0x00, 0x00,
}
