// Code generated by protoc-gen-go. DO NOT EDIT.
// source: outboxmessage.proto

package outbox

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import any "github.com/golang/protobuf/ptypes/any"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// OutboxMessage is a protocol buffers
type OutboxMessage struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	CausationId          string   `protobuf:"bytes,2,opt,name=causation_id,json=causationId" json:"causation_id,omitempty"`
	CorrelationId        string   `protobuf:"bytes,3,opt,name=correlation_id,json=correlationId" json:"correlation_id,omitempty"`
	Time                 string   `protobuf:"bytes,4,opt,name=time" json:"time,omitempty"`
	ContentType          string   `protobuf:"bytes,5,opt,name=content_type,json=contentType" json:"content_type,omitempty"`
	Body                 *any.Any `protobuf:"bytes,6,opt,name=body" json:"body,omitempty"`
	Operation            int32    `protobuf:"varint,7,opt,name=operation" json:"operation,omitempty"`
	DestinationEndpoint  string   `protobuf:"bytes,8,opt,name=destination_endpoint,json=destinationEndpoint" json:"destination_endpoint,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OutboxMessage) Reset()         { *m = OutboxMessage{} }
func (m *OutboxMessage) String() string { return proto.CompactTextString(m) }
func (*OutboxMessage) ProtoMessage()    {}
func (*OutboxMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_outboxmessage_4953118a46914bef, []int{0}
}
func (m *OutboxMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OutboxMessage.Unmarshal(m, b)
}
func (m *OutboxMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OutboxMessage.Marshal(b, m, deterministic)
}
func (dst *OutboxMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OutboxMessage.Merge(dst, src)
}
func (m *OutboxMessage) XXX_Size() int {
	return xxx_messageInfo_OutboxMessage.Size(m)
}
func (m *OutboxMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_OutboxMessage.DiscardUnknown(m)
}

var xxx_messageInfo_OutboxMessage proto.InternalMessageInfo

func (m *OutboxMessage) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *OutboxMessage) GetCausationId() string {
	if m != nil {
		return m.CausationId
	}
	return ""
}

func (m *OutboxMessage) GetCorrelationId() string {
	if m != nil {
		return m.CorrelationId
	}
	return ""
}

func (m *OutboxMessage) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

func (m *OutboxMessage) GetContentType() string {
	if m != nil {
		return m.ContentType
	}
	return ""
}

func (m *OutboxMessage) GetBody() *any.Any {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *OutboxMessage) GetOperation() int32 {
	if m != nil {
		return m.Operation
	}
	return 0
}

func (m *OutboxMessage) GetDestinationEndpoint() string {
	if m != nil {
		return m.DestinationEndpoint
	}
	return ""
}

func init() {
	proto.RegisterType((*OutboxMessage)(nil), "axbolt.outbox.OutboxMessage")
}

func init() { proto.RegisterFile("outboxmessage.proto", fileDescriptor_outboxmessage_4953118a46914bef) }

var fileDescriptor_outboxmessage_4953118a46914bef = []byte{
	// 262 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0x49, 0x4c, 0x63, 0xbb, 0x35, 0x3d, 0x6c, 0x7b, 0x58, 0xc5, 0x43, 0x14, 0x84, 0x9c,
	0x52, 0xd4, 0x27, 0x50, 0xf0, 0xd0, 0x83, 0x08, 0xc1, 0x93, 0x97, 0x92, 0x74, 0xc7, 0xb0, 0x90,
	0xee, 0x2c, 0xc9, 0x04, 0xba, 0xcf, 0xe2, 0xcb, 0x0a, 0xb3, 0xb5, 0xf6, 0x16, 0xfe, 0xef, 0xe3,
	0xff, 0x33, 0x2b, 0x96, 0x38, 0x52, 0x83, 0x87, 0x3d, 0x0c, 0x43, 0xdd, 0x42, 0xe9, 0x7a, 0x24,
	0x94, 0x59, 0x7d, 0x68, 0xb0, 0xa3, 0x32, 0xb0, 0x9b, 0xeb, 0x16, 0xb1, 0xed, 0x60, 0xcd, 0xb0,
	0x19, 0xbf, 0xd7, 0xb5, 0xf5, 0xc1, 0xbc, 0xff, 0x89, 0x45, 0xf6, 0xc1, 0xd6, 0x7b, 0x68, 0x90,
	0x0b, 0x11, 0x1b, 0xad, 0xa2, 0x3c, 0x2a, 0x66, 0x55, 0x6c, 0xb4, 0xbc, 0x13, 0x57, 0xbb, 0x7a,
	0x1c, 0x6a, 0x32, 0x68, 0xb7, 0x46, 0xab, 0x98, 0xc9, 0xfc, 0x94, 0x6d, 0xb4, 0x7c, 0x10, 0x8b,
	0x1d, 0xf6, 0x3d, 0x74, 0x27, 0xe9, 0x82, 0xa5, 0xec, 0x2c, 0xdd, 0x68, 0x29, 0x45, 0x42, 0x66,
	0x0f, 0x2a, 0x61, 0xc8, 0xdf, 0xdc, 0x8e, 0x96, 0xc0, 0xd2, 0x96, 0xbc, 0x03, 0x35, 0x39, 0xb6,
	0x87, 0xec, 0xd3, 0x3b, 0x90, 0x85, 0x48, 0x1a, 0xd4, 0x5e, 0xa5, 0x79, 0x54, 0xcc, 0x9f, 0x56,
	0x65, 0x38, 0xa6, 0xfc, 0x3b, 0xa6, 0x7c, 0xb1, 0xbe, 0x62, 0x43, 0xde, 0x8a, 0x19, 0x3a, 0xe8,
	0x79, 0x4f, 0x5d, 0xe6, 0x51, 0x31, 0xa9, 0xfe, 0x03, 0xf9, 0x28, 0x56, 0x1a, 0x06, 0x32, 0x36,
	0xfc, 0x25, 0x58, 0xed, 0xd0, 0x58, 0x52, 0x53, 0x9e, 0x5c, 0x9e, 0xb1, 0xb7, 0x23, 0x7a, 0x9d,
	0x7e, 0xa5, 0xe1, 0x09, 0x9b, 0x94, 0xe7, 0x9e, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0xb3, 0x26,
	0xa3, 0xb0, 0x6f, 0x01, 0x00, 0x00,
}
