// Code generated by protoc-gen-go. DO NOT EDIT.
// source: src/axbolt/messagestore/storedmessage.proto

package messagestore

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import any "github.com/golang/protobuf/ptypes/any"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// StoredMessage is a container for holding stored message-specific data that is
// serialized into the protobuf format before being persisted in a Bolt bucket
type StoredMessage struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CausationId          string   `protobuf:"bytes,2,opt,name=causation_id,json=causationId,proto3" json:"causation_id,omitempty"`
	CorrelationId        string   `protobuf:"bytes,3,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	CreatedAt            string   `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	SendAt               string   `protobuf:"bytes,5,opt,name=send_at,json=sendAt,proto3" json:"send_at,omitempty"`
	Message              *any.Any `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StoredMessage) Reset()         { *m = StoredMessage{} }
func (m *StoredMessage) String() string { return proto.CompactTextString(m) }
func (*StoredMessage) ProtoMessage()    {}
func (*StoredMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_storedmessage_030c007e8c43780d, []int{0}
}
func (m *StoredMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StoredMessage.Unmarshal(m, b)
}
func (m *StoredMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StoredMessage.Marshal(b, m, deterministic)
}
func (dst *StoredMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoredMessage.Merge(dst, src)
}
func (m *StoredMessage) XXX_Size() int {
	return xxx_messageInfo_StoredMessage.Size(m)
}
func (m *StoredMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_StoredMessage.DiscardUnknown(m)
}

var xxx_messageInfo_StoredMessage proto.InternalMessageInfo

func (m *StoredMessage) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *StoredMessage) GetCausationId() string {
	if m != nil {
		return m.CausationId
	}
	return ""
}

func (m *StoredMessage) GetCorrelationId() string {
	if m != nil {
		return m.CorrelationId
	}
	return ""
}

func (m *StoredMessage) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *StoredMessage) GetSendAt() string {
	if m != nil {
		return m.SendAt
	}
	return ""
}

func (m *StoredMessage) GetMessage() *any.Any {
	if m != nil {
		return m.Message
	}
	return nil
}

func init() {
	proto.RegisterType((*StoredMessage)(nil), "axbolt.outbox.StoredMessage")
}

func init() {
	proto.RegisterFile("src/axbolt/messagestore/storedmessage.proto", fileDescriptor_storedmessage_030c007e8c43780d)
}

var fileDescriptor_storedmessage_030c007e8c43780d = []byte{
	// 237 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0x49, 0xd4, 0x94, 0x4e, 0x9b, 0x1c, 0x16, 0xc1, 0x28, 0x08, 0x55, 0x10, 0x0a, 0xc2,
	0x2e, 0xe8, 0x13, 0xc4, 0x5b, 0x0f, 0x5e, 0xea, 0xcd, 0x4b, 0xd9, 0x64, 0xc7, 0x10, 0x88, 0x19,
	0xd9, 0x9d, 0x40, 0xfb, 0x98, 0xbe, 0x91, 0x38, 0x9b, 0x96, 0x5e, 0x16, 0xf6, 0xff, 0x3e, 0x7e,
	0xf8, 0x07, 0x9e, 0x83, 0x6f, 0x8c, 0xdd, 0xd7, 0xd4, 0xb3, 0xf9, 0xc6, 0x10, 0x6c, 0x8b, 0x81,
	0xc9, 0xa3, 0x91, 0xd7, 0x4d, 0x91, 0xfe, 0xf1, 0xc4, 0xa4, 0xf2, 0x28, 0x6a, 0x1a, 0xb9, 0xa6,
	0xfd, 0xdd, 0x6d, 0x4b, 0xd4, 0xf6, 0x68, 0x04, 0xd6, 0xe3, 0x97, 0xb1, 0xc3, 0x21, 0x9a, 0x8f,
	0xbf, 0x09, 0xe4, 0x1f, 0xd2, 0xf0, 0x1e, 0x1b, 0x54, 0x01, 0x69, 0xe7, 0xca, 0x64, 0x95, 0xac,
	0xe7, 0xdb, 0xb4, 0x73, 0xea, 0x01, 0x96, 0x8d, 0x1d, 0x83, 0xe5, 0x8e, 0x86, 0x5d, 0xe7, 0xca,
	0x54, 0xc8, 0xe2, 0x94, 0x6d, 0x9c, 0x7a, 0x82, 0xa2, 0x21, 0xef, 0xb1, 0x3f, 0x49, 0x17, 0x22,
	0xe5, 0x67, 0xe9, 0xc6, 0xa9, 0x7b, 0x80, 0xc6, 0xa3, 0x65, 0x74, 0x3b, 0xcb, 0xe5, 0xa5, 0x28,
	0xf3, 0x29, 0xa9, 0x58, 0xdd, 0xc0, 0x2c, 0xe0, 0x20, 0xec, 0x4a, 0x58, 0xf6, 0xff, 0xad, 0x58,
	0x69, 0x98, 0x4d, 0xf3, 0xca, 0x6c, 0x95, 0xac, 0x17, 0x2f, 0xd7, 0x3a, 0x0e, 0xd2, 0xc7, 0x41,
	0xba, 0x1a, 0x0e, 0xdb, 0xa3, 0xf4, 0x56, 0x7c, 0x2e, 0xcf, 0x2f, 0x54, 0x67, 0xa2, 0xbd, 0xfe,
	0x05, 0x00, 0x00, 0xff, 0xff, 0x4e, 0xd4, 0xcb, 0x5e, 0x43, 0x01, 0x00, 0x00,
}
