// Code generated by protoc-gen-go. DO NOT EDIT.
// source: src/axbolt/saga/sagasnapshot.proto

package saga

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import any "github.com/golang/protobuf/ptypes/any"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// SagaSnapshot is a container for a saga snapshot serialized into the
// protobuf format before being persisted in a Bolt bucket
type SagaSnapshot struct {
	InstanceId           string   `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Revision             int64    `protobuf:"varint,2,opt,name=revision,proto3" json:"revision,omitempty"`
	PersistenceKey       string   `protobuf:"bytes,3,opt,name=persistence_key,json=persistenceKey,proto3" json:"persistence_key,omitempty"`
	Data                 *any.Any `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	InsertTime           string   `protobuf:"bytes,5,opt,name=insert_time,json=insertTime,proto3" json:"insert_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SagaSnapshot) Reset()         { *m = SagaSnapshot{} }
func (m *SagaSnapshot) String() string { return proto.CompactTextString(m) }
func (*SagaSnapshot) ProtoMessage()    {}
func (*SagaSnapshot) Descriptor() ([]byte, []int) {
	return fileDescriptor_sagasnapshot_b75bd85524937af8, []int{0}
}
func (m *SagaSnapshot) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SagaSnapshot.Unmarshal(m, b)
}
func (m *SagaSnapshot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SagaSnapshot.Marshal(b, m, deterministic)
}
func (dst *SagaSnapshot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SagaSnapshot.Merge(dst, src)
}
func (m *SagaSnapshot) XXX_Size() int {
	return xxx_messageInfo_SagaSnapshot.Size(m)
}
func (m *SagaSnapshot) XXX_DiscardUnknown() {
	xxx_messageInfo_SagaSnapshot.DiscardUnknown(m)
}

var xxx_messageInfo_SagaSnapshot proto.InternalMessageInfo

func (m *SagaSnapshot) GetInstanceId() string {
	if m != nil {
		return m.InstanceId
	}
	return ""
}

func (m *SagaSnapshot) GetRevision() int64 {
	if m != nil {
		return m.Revision
	}
	return 0
}

func (m *SagaSnapshot) GetPersistenceKey() string {
	if m != nil {
		return m.PersistenceKey
	}
	return ""
}

func (m *SagaSnapshot) GetData() *any.Any {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *SagaSnapshot) GetInsertTime() string {
	if m != nil {
		return m.InsertTime
	}
	return ""
}

func init() {
	proto.RegisterType((*SagaSnapshot)(nil), "axbolt.saga.SagaSnapshot")
}

func init() {
	proto.RegisterFile("src/axbolt/saga/sagasnapshot.proto", fileDescriptor_sagasnapshot_b75bd85524937af8)
}

var fileDescriptor_sagasnapshot_b75bd85524937af8 = []byte{
	// 228 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0xbd, 0x4e, 0xc3, 0x30,
	0x10, 0xc7, 0x65, 0x1a, 0x2a, 0x70, 0x10, 0x48, 0x16, 0x83, 0xe9, 0x42, 0xd4, 0x85, 0x4c, 0x8e,
	0x04, 0x4f, 0x00, 0x1b, 0x62, 0x4b, 0x99, 0x58, 0xaa, 0x4b, 0x73, 0x18, 0x8b, 0xd6, 0x8e, 0x7c,
	0x07, 0xc2, 0x4f, 0xc7, 0xab, 0xa1, 0x38, 0x6d, 0xc5, 0x72, 0xd2, 0xfd, 0x3f, 0x4e, 0xbf, 0x93,
	0x4b, 0x8a, 0x9b, 0x06, 0x7e, 0xba, 0xb0, 0xe5, 0x86, 0xc0, 0x42, 0x1e, 0xe4, 0x61, 0xa0, 0x8f,
	0xc0, 0x66, 0x88, 0x81, 0x83, 0x2a, 0x27, 0xdf, 0x8c, 0xd6, 0xe2, 0xc6, 0x86, 0x60, 0xb7, 0xd8,
	0x64, 0xab, 0xfb, 0x7a, 0x6f, 0xc0, 0xa7, 0x29, 0xb7, 0xfc, 0x15, 0xf2, 0x62, 0x05, 0x16, 0x56,
	0xfb, 0xba, 0xba, 0x95, 0xa5, 0xf3, 0xc4, 0xe0, 0x37, 0xb8, 0x76, 0xbd, 0x16, 0x95, 0xa8, 0xcf,
	0x5b, 0x79, 0x90, 0x9e, 0x7b, 0xb5, 0x90, 0x67, 0x11, 0xbf, 0x1d, 0xb9, 0xe0, 0xf5, 0x49, 0x25,
	0xea, 0x59, 0x7b, 0xdc, 0xd5, 0x9d, 0xbc, 0x1a, 0x30, 0x92, 0x23, 0xc6, 0xb1, 0xff, 0x89, 0x49,
	0xcf, 0xf2, 0x81, 0xcb, 0x7f, 0xf2, 0x0b, 0x26, 0x55, 0xcb, 0xa2, 0x07, 0x06, 0x5d, 0x54, 0xa2,
	0x2e, 0xef, 0xaf, 0xcd, 0x04, 0x68, 0x0e, 0x80, 0xe6, 0xd1, 0xa7, 0x36, 0x27, 0xf6, 0x3c, 0x18,
	0x79, 0xcd, 0x6e, 0x87, 0xfa, 0xf4, 0xc8, 0x83, 0x91, 0x5f, 0xdd, 0x0e, 0x9f, 0xe6, 0x6f, 0xc5,
	0xf8, 0x64, 0x37, 0xcf, 0xe5, 0x87, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xdd, 0xc6, 0xd9, 0x2f,
	0x1e, 0x01, 0x00, 0x00,
}
