// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sagainstance.proto

package saga

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import any "github.com/golang/protobuf/ptypes/any"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// SagaInstance is a container for a saga instance serialized into the
// protobuf format before being persisted in a Bolt bucket
type SagaInstance struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Revision             int64    `protobuf:"varint,2,opt,name=revision,proto3" json:"revision,omitempty"`
	PersistenceKey       string   `protobuf:"bytes,3,opt,name=persistence_key,json=persistenceKey,proto3" json:"persistence_key,omitempty"`
	Data                 *any.Any `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	InsertTime           string   `protobuf:"bytes,6,opt,name=insert_time,json=insertTime,proto3" json:"insert_time,omitempty"`
	UpdateTime           string   `protobuf:"bytes,7,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SagaInstance) Reset()         { *m = SagaInstance{} }
func (m *SagaInstance) String() string { return proto.CompactTextString(m) }
func (*SagaInstance) ProtoMessage()    {}
func (*SagaInstance) Descriptor() ([]byte, []int) {
	return fileDescriptor_sagainstance_ae38b0ddec523155, []int{0}
}
func (m *SagaInstance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SagaInstance.Unmarshal(m, b)
}
func (m *SagaInstance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SagaInstance.Marshal(b, m, deterministic)
}
func (dst *SagaInstance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SagaInstance.Merge(dst, src)
}
func (m *SagaInstance) XXX_Size() int {
	return xxx_messageInfo_SagaInstance.Size(m)
}
func (m *SagaInstance) XXX_DiscardUnknown() {
	xxx_messageInfo_SagaInstance.DiscardUnknown(m)
}

var xxx_messageInfo_SagaInstance proto.InternalMessageInfo

func (m *SagaInstance) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SagaInstance) GetRevision() int64 {
	if m != nil {
		return m.Revision
	}
	return 0
}

func (m *SagaInstance) GetPersistenceKey() string {
	if m != nil {
		return m.PersistenceKey
	}
	return ""
}

func (m *SagaInstance) GetData() *any.Any {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *SagaInstance) GetInsertTime() string {
	if m != nil {
		return m.InsertTime
	}
	return ""
}

func (m *SagaInstance) GetUpdateTime() string {
	if m != nil {
		return m.UpdateTime
	}
	return ""
}

func init() {
	proto.RegisterType((*SagaInstance)(nil), "axbolt.saga.SagaInstance")
}

func init() { proto.RegisterFile("sagainstance.proto", fileDescriptor_sagainstance_ae38b0ddec523155) }

var fileDescriptor_sagainstance_ae38b0ddec523155 = []byte{
	// 229 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0xe5, 0xb4, 0x04, 0xb8, 0xa0, 0x22, 0x59, 0x0c, 0xa6, 0x0b, 0x11, 0x0b, 0x99, 0x5c,
	0x09, 0x7e, 0x01, 0x6c, 0x88, 0x2d, 0x30, 0xb1, 0x54, 0x97, 0xe6, 0x88, 0x4e, 0xb4, 0x76, 0x14,
	0x5f, 0x10, 0xf9, 0x95, 0xfc, 0x25, 0x14, 0x1b, 0x10, 0xe3, 0xbd, 0xf7, 0xbd, 0xa7, 0x77, 0xa0,
	0x03, 0x76, 0xc8, 0x2e, 0x08, 0xba, 0x1d, 0xd9, 0x7e, 0xf0, 0xe2, 0x75, 0x81, 0x9f, 0x8d, 0xdf,
	0x8b, 0x9d, 0xad, 0xf5, 0x65, 0xe7, 0x7d, 0xb7, 0xa7, 0x4d, 0xb4, 0x9a, 0xf1, 0x6d, 0x83, 0x6e,
	0x4a, 0xdc, 0xf5, 0x97, 0x82, 0xb3, 0x67, 0xec, 0xf0, 0xf1, 0x27, 0xae, 0x57, 0x90, 0x71, 0x6b,
	0x54, 0xa9, 0xaa, 0xd3, 0x3a, 0xe3, 0x56, 0xaf, 0xe1, 0x64, 0xa0, 0x0f, 0x0e, 0xec, 0x9d, 0xc9,
	0x4a, 0x55, 0x2d, 0xea, 0xbf, 0x5b, 0xdf, 0xc0, 0x79, 0x4f, 0x43, 0xe0, 0x20, 0xe4, 0x76, 0xb4,
	0x7d, 0xa7, 0xc9, 0x2c, 0x62, 0x70, 0xf5, 0x4f, 0x7e, 0xa2, 0x49, 0x57, 0xb0, 0x6c, 0x51, 0xd0,
	0x1c, 0x95, 0xaa, 0x2a, 0x6e, 0x2f, 0x6c, 0xda, 0x63, 0x7f, 0xf7, 0xd8, 0x7b, 0x37, 0xd5, 0x91,
	0xd0, 0x57, 0x50, 0xb0, 0x0b, 0x34, 0xc8, 0x56, 0xf8, 0x40, 0x26, 0x8f, 0x75, 0x90, 0xa4, 0x17,
	0x3e, 0xd0, 0x0c, 0x8c, 0x7d, 0x8b, 0x42, 0x09, 0x38, 0x4e, 0x40, 0x92, 0x66, 0xe0, 0x21, 0x7f,
	0x5d, 0xce, 0x4f, 0x37, 0x79, 0x6c, 0xbf, 0xfb, 0x0e, 0x00, 0x00, 0xff, 0xff, 0xbd, 0x5a, 0xdb,
	0x77, 0x1e, 0x01, 0x00, 0x00,
}
