// Code generated by protoc-gen-go. DO NOT EDIT.
// source: src/axbolt/saga/sagakeyset.proto

package saga

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// SagaKeySet is a container for a saga keset values serialized into the
// protobuf format before being persisted in a Bolt bucket
type SagaKeySet struct {
	InstanceId           string   `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	PersistenceKey       string   `protobuf:"bytes,2,opt,name=persistence_key,json=persistenceKey,proto3" json:"persistence_key,omitempty"`
	MappingKeys          []string `protobuf:"bytes,3,rep,name=mapping_keys,json=mappingKeys,proto3" json:"mapping_keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SagaKeySet) Reset()         { *m = SagaKeySet{} }
func (m *SagaKeySet) String() string { return proto.CompactTextString(m) }
func (*SagaKeySet) ProtoMessage()    {}
func (*SagaKeySet) Descriptor() ([]byte, []int) {
	return fileDescriptor_sagakeyset_b885ceffc68d106d, []int{0}
}
func (m *SagaKeySet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SagaKeySet.Unmarshal(m, b)
}
func (m *SagaKeySet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SagaKeySet.Marshal(b, m, deterministic)
}
func (dst *SagaKeySet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SagaKeySet.Merge(dst, src)
}
func (m *SagaKeySet) XXX_Size() int {
	return xxx_messageInfo_SagaKeySet.Size(m)
}
func (m *SagaKeySet) XXX_DiscardUnknown() {
	xxx_messageInfo_SagaKeySet.DiscardUnknown(m)
}

var xxx_messageInfo_SagaKeySet proto.InternalMessageInfo

func (m *SagaKeySet) GetInstanceId() string {
	if m != nil {
		return m.InstanceId
	}
	return ""
}

func (m *SagaKeySet) GetPersistenceKey() string {
	if m != nil {
		return m.PersistenceKey
	}
	return ""
}

func (m *SagaKeySet) GetMappingKeys() []string {
	if m != nil {
		return m.MappingKeys
	}
	return nil
}

func init() {
	proto.RegisterType((*SagaKeySet)(nil), "axbolt.saga.SagaKeySet")
}

func init() {
	proto.RegisterFile("src/axbolt/saga/sagakeyset.proto", fileDescriptor_sagakeyset_b885ceffc68d106d)
}

var fileDescriptor_sagakeyset_b885ceffc68d106d = []byte{
	// 168 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8e, 0xb1, 0x0e, 0x82, 0x40,
	0x10, 0x05, 0x83, 0x18, 0x12, 0x16, 0xa3, 0xc9, 0x55, 0x74, 0xa2, 0x8d, 0x54, 0x50, 0xf8, 0x07,
	0x76, 0x86, 0x0e, 0x3a, 0x1b, 0xb3, 0xc0, 0x86, 0x5c, 0x50, 0xb8, 0xb0, 0x57, 0xb8, 0x7f, 0x6f,
	0xee, 0xd4, 0xc4, 0xe6, 0x15, 0xf3, 0xa6, 0x18, 0xc8, 0x78, 0xe9, 0x4a, 0x7c, 0xb5, 0xf3, 0xc3,
	0x96, 0x8c, 0x03, 0xfa, 0x19, 0x49, 0x98, 0x6c, 0x61, 0x96, 0xd9, 0xce, 0x2a, 0xf9, 0xbc, 0x85,
	0x3b, 0x8e, 0x02, 0xd0, 0xe0, 0x80, 0x15, 0x49, 0x43, 0x56, 0xed, 0x21, 0xd1, 0x13, 0x5b, 0x9c,
	0x3a, 0xba, 0xeb, 0x3e, 0x0d, 0xb2, 0x20, 0x8f, 0x6b, 0xf8, 0xa1, 0x6b, 0xaf, 0x4e, 0xb0, 0x33,
	0xb4, 0xb0, 0x66, 0x4b, 0xce, 0x19, 0x49, 0xd2, 0x95, 0x97, 0xb6, 0x7f, 0xb8, 0x22, 0x51, 0x07,
	0xd8, 0x3c, 0xd1, 0x18, 0x3d, 0x0d, 0x4e, 0xe2, 0x34, 0xcc, 0xc2, 0x3c, 0xae, 0x93, 0x2f, 0xab,
	0x48, 0xf8, 0x12, 0xdd, 0xd6, 0x2e, 0xa1, 0x8d, 0x7c, 0xd6, 0xf9, 0x1d, 0x00, 0x00, 0xff, 0xff,
	0x2a, 0xc3, 0x48, 0xd4, 0xba, 0x00, 0x00, 0x00,
}
