// Code generated by protoc-gen-go. DO NOT EDIT.
// source: src/axtest/testmessages/messages.proto

package testmessages

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Message is a protocol buffers message that implements ax.Message.
type Message struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_96dc454175151548, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// MessageA is a protocol buffers message that implements ax.Message.
type MessageA struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageA) Reset()         { *m = MessageA{} }
func (m *MessageA) String() string { return proto.CompactTextString(m) }
func (*MessageA) ProtoMessage()    {}
func (*MessageA) Descriptor() ([]byte, []int) {
	return fileDescriptor_96dc454175151548, []int{1}
}

func (m *MessageA) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageA.Unmarshal(m, b)
}
func (m *MessageA) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageA.Marshal(b, m, deterministic)
}
func (m *MessageA) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageA.Merge(m, src)
}
func (m *MessageA) XXX_Size() int {
	return xxx_messageInfo_MessageA.Size(m)
}
func (m *MessageA) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageA.DiscardUnknown(m)
}

var xxx_messageInfo_MessageA proto.InternalMessageInfo

func (m *MessageA) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// MessageB is a protocol buffers message that implements ax.Message.
type MessageB struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageB) Reset()         { *m = MessageB{} }
func (m *MessageB) String() string { return proto.CompactTextString(m) }
func (*MessageB) ProtoMessage()    {}
func (*MessageB) Descriptor() ([]byte, []int) {
	return fileDescriptor_96dc454175151548, []int{2}
}

func (m *MessageB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageB.Unmarshal(m, b)
}
func (m *MessageB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageB.Marshal(b, m, deterministic)
}
func (m *MessageB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageB.Merge(m, src)
}
func (m *MessageB) XXX_Size() int {
	return xxx_messageInfo_MessageB.Size(m)
}
func (m *MessageB) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageB.DiscardUnknown(m)
}

var xxx_messageInfo_MessageB proto.InternalMessageInfo

func (m *MessageB) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// MessageC is a protocol buffers message that implements ax.Message.
type MessageC struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageC) Reset()         { *m = MessageC{} }
func (m *MessageC) String() string { return proto.CompactTextString(m) }
func (*MessageC) ProtoMessage()    {}
func (*MessageC) Descriptor() ([]byte, []int) {
	return fileDescriptor_96dc454175151548, []int{3}
}

func (m *MessageC) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageC.Unmarshal(m, b)
}
func (m *MessageC) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageC.Marshal(b, m, deterministic)
}
func (m *MessageC) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageC.Merge(m, src)
}
func (m *MessageC) XXX_Size() int {
	return xxx_messageInfo_MessageC.Size(m)
}
func (m *MessageC) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageC.DiscardUnknown(m)
}

var xxx_messageInfo_MessageC proto.InternalMessageInfo

func (m *MessageC) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// MessageD is a protocol buffers message that implements ax.Message.
type MessageD struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageD) Reset()         { *m = MessageD{} }
func (m *MessageD) String() string { return proto.CompactTextString(m) }
func (*MessageD) ProtoMessage()    {}
func (*MessageD) Descriptor() ([]byte, []int) {
	return fileDescriptor_96dc454175151548, []int{4}
}

func (m *MessageD) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageD.Unmarshal(m, b)
}
func (m *MessageD) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageD.Marshal(b, m, deterministic)
}
func (m *MessageD) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageD.Merge(m, src)
}
func (m *MessageD) XXX_Size() int {
	return xxx_messageInfo_MessageD.Size(m)
}
func (m *MessageD) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageD.DiscardUnknown(m)
}

var xxx_messageInfo_MessageD proto.InternalMessageInfo

func (m *MessageD) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// MessageE is a protocol buffers message that implements ax.Message.
type MessageE struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageE) Reset()         { *m = MessageE{} }
func (m *MessageE) String() string { return proto.CompactTextString(m) }
func (*MessageE) ProtoMessage()    {}
func (*MessageE) Descriptor() ([]byte, []int) {
	return fileDescriptor_96dc454175151548, []int{5}
}

func (m *MessageE) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageE.Unmarshal(m, b)
}
func (m *MessageE) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageE.Marshal(b, m, deterministic)
}
func (m *MessageE) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageE.Merge(m, src)
}
func (m *MessageE) XXX_Size() int {
	return xxx_messageInfo_MessageE.Size(m)
}
func (m *MessageE) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageE.DiscardUnknown(m)
}

var xxx_messageInfo_MessageE proto.InternalMessageInfo

func (m *MessageE) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// MessageF is a protocol buffers message that implements ax.Message.
type MessageF struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageF) Reset()         { *m = MessageF{} }
func (m *MessageF) String() string { return proto.CompactTextString(m) }
func (*MessageF) ProtoMessage()    {}
func (*MessageF) Descriptor() ([]byte, []int) {
	return fileDescriptor_96dc454175151548, []int{6}
}

func (m *MessageF) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageF.Unmarshal(m, b)
}
func (m *MessageF) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageF.Marshal(b, m, deterministic)
}
func (m *MessageF) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageF.Merge(m, src)
}
func (m *MessageF) XXX_Size() int {
	return xxx_messageInfo_MessageF.Size(m)
}
func (m *MessageF) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageF.DiscardUnknown(m)
}

var xxx_messageInfo_MessageF proto.InternalMessageInfo

func (m *MessageF) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// Command is a protocol buffers message that implements ax.Command.
type Command struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Command) Reset()         { *m = Command{} }
func (m *Command) String() string { return proto.CompactTextString(m) }
func (*Command) ProtoMessage()    {}
func (*Command) Descriptor() ([]byte, []int) {
	return fileDescriptor_96dc454175151548, []int{7}
}

func (m *Command) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Command.Unmarshal(m, b)
}
func (m *Command) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Command.Marshal(b, m, deterministic)
}
func (m *Command) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Command.Merge(m, src)
}
func (m *Command) XXX_Size() int {
	return xxx_messageInfo_Command.Size(m)
}
func (m *Command) XXX_DiscardUnknown() {
	xxx_messageInfo_Command.DiscardUnknown(m)
}

var xxx_messageInfo_Command proto.InternalMessageInfo

func (m *Command) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// SelfValidatingCommand is a protocol buffers message that
// implements both ax.Command and endpoint.SelfValidatingMessage.
type SelfValidatingCommand struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SelfValidatingCommand) Reset()         { *m = SelfValidatingCommand{} }
func (m *SelfValidatingCommand) String() string { return proto.CompactTextString(m) }
func (*SelfValidatingCommand) ProtoMessage()    {}
func (*SelfValidatingCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_96dc454175151548, []int{8}
}

func (m *SelfValidatingCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SelfValidatingCommand.Unmarshal(m, b)
}
func (m *SelfValidatingCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SelfValidatingCommand.Marshal(b, m, deterministic)
}
func (m *SelfValidatingCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SelfValidatingCommand.Merge(m, src)
}
func (m *SelfValidatingCommand) XXX_Size() int {
	return xxx_messageInfo_SelfValidatingCommand.Size(m)
}
func (m *SelfValidatingCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_SelfValidatingCommand.DiscardUnknown(m)
}

var xxx_messageInfo_SelfValidatingCommand proto.InternalMessageInfo

func (m *SelfValidatingCommand) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// FailedSelfValidatingCommand is a protocol buffers message that
// implements both ax.Command and endpoint.SelfValidatingMessage.
// Its Validate method returns validation error to test failure
// scenarios in unit tests
type FailedSelfValidatingCommand struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FailedSelfValidatingCommand) Reset()         { *m = FailedSelfValidatingCommand{} }
func (m *FailedSelfValidatingCommand) String() string { return proto.CompactTextString(m) }
func (*FailedSelfValidatingCommand) ProtoMessage()    {}
func (*FailedSelfValidatingCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_96dc454175151548, []int{9}
}

func (m *FailedSelfValidatingCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FailedSelfValidatingCommand.Unmarshal(m, b)
}
func (m *FailedSelfValidatingCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FailedSelfValidatingCommand.Marshal(b, m, deterministic)
}
func (m *FailedSelfValidatingCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FailedSelfValidatingCommand.Merge(m, src)
}
func (m *FailedSelfValidatingCommand) XXX_Size() int {
	return xxx_messageInfo_FailedSelfValidatingCommand.Size(m)
}
func (m *FailedSelfValidatingCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_FailedSelfValidatingCommand.DiscardUnknown(m)
}

var xxx_messageInfo_FailedSelfValidatingCommand proto.InternalMessageInfo

func (m *FailedSelfValidatingCommand) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// Event is a protocol buffers message that implements ax.Event.
type Event struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_96dc454175151548, []int{10}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// SelfValidatingEvent is a protocol buffers message that
// implements both ax.Event and endpoint.SelfValidatingMessage.
type SelfValidatingEvent struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SelfValidatingEvent) Reset()         { *m = SelfValidatingEvent{} }
func (m *SelfValidatingEvent) String() string { return proto.CompactTextString(m) }
func (*SelfValidatingEvent) ProtoMessage()    {}
func (*SelfValidatingEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_96dc454175151548, []int{11}
}

func (m *SelfValidatingEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SelfValidatingEvent.Unmarshal(m, b)
}
func (m *SelfValidatingEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SelfValidatingEvent.Marshal(b, m, deterministic)
}
func (m *SelfValidatingEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SelfValidatingEvent.Merge(m, src)
}
func (m *SelfValidatingEvent) XXX_Size() int {
	return xxx_messageInfo_SelfValidatingEvent.Size(m)
}
func (m *SelfValidatingEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_SelfValidatingEvent.DiscardUnknown(m)
}

var xxx_messageInfo_SelfValidatingEvent proto.InternalMessageInfo

func (m *SelfValidatingEvent) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// FailedSelfValidatingEvent is a protocol buffers message that
// implements both ax.Event and endpoint.SelfValidatingMessage.
// Its Validate method returns validation error to test failure
// scenarios in unit tests
type FailedSelfValidatingEvent struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FailedSelfValidatingEvent) Reset()         { *m = FailedSelfValidatingEvent{} }
func (m *FailedSelfValidatingEvent) String() string { return proto.CompactTextString(m) }
func (*FailedSelfValidatingEvent) ProtoMessage()    {}
func (*FailedSelfValidatingEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_96dc454175151548, []int{12}
}

func (m *FailedSelfValidatingEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FailedSelfValidatingEvent.Unmarshal(m, b)
}
func (m *FailedSelfValidatingEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FailedSelfValidatingEvent.Marshal(b, m, deterministic)
}
func (m *FailedSelfValidatingEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FailedSelfValidatingEvent.Merge(m, src)
}
func (m *FailedSelfValidatingEvent) XXX_Size() int {
	return xxx_messageInfo_FailedSelfValidatingEvent.Size(m)
}
func (m *FailedSelfValidatingEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_FailedSelfValidatingEvent.DiscardUnknown(m)
}

var xxx_messageInfo_FailedSelfValidatingEvent proto.InternalMessageInfo

func (m *FailedSelfValidatingEvent) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// NonAxMessage is a protocol buffers message that does not implement ax.Message.
type NonAxMessage struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NonAxMessage) Reset()         { *m = NonAxMessage{} }
func (m *NonAxMessage) String() string { return proto.CompactTextString(m) }
func (*NonAxMessage) ProtoMessage()    {}
func (*NonAxMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_96dc454175151548, []int{13}
}

func (m *NonAxMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NonAxMessage.Unmarshal(m, b)
}
func (m *NonAxMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NonAxMessage.Marshal(b, m, deterministic)
}
func (m *NonAxMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NonAxMessage.Merge(m, src)
}
func (m *NonAxMessage) XXX_Size() int {
	return xxx_messageInfo_NonAxMessage.Size(m)
}
func (m *NonAxMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_NonAxMessage.DiscardUnknown(m)
}

var xxx_messageInfo_NonAxMessage proto.InternalMessageInfo

func (m *NonAxMessage) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*Message)(nil), "axtest.testmessages.Message")
	proto.RegisterType((*MessageA)(nil), "axtest.testmessages.MessageA")
	proto.RegisterType((*MessageB)(nil), "axtest.testmessages.MessageB")
	proto.RegisterType((*MessageC)(nil), "axtest.testmessages.MessageC")
	proto.RegisterType((*MessageD)(nil), "axtest.testmessages.MessageD")
	proto.RegisterType((*MessageE)(nil), "axtest.testmessages.MessageE")
	proto.RegisterType((*MessageF)(nil), "axtest.testmessages.MessageF")
	proto.RegisterType((*Command)(nil), "axtest.testmessages.Command")
	proto.RegisterType((*SelfValidatingCommand)(nil), "axtest.testmessages.SelfValidatingCommand")
	proto.RegisterType((*FailedSelfValidatingCommand)(nil), "axtest.testmessages.FailedSelfValidatingCommand")
	proto.RegisterType((*Event)(nil), "axtest.testmessages.Event")
	proto.RegisterType((*SelfValidatingEvent)(nil), "axtest.testmessages.SelfValidatingEvent")
	proto.RegisterType((*FailedSelfValidatingEvent)(nil), "axtest.testmessages.FailedSelfValidatingEvent")
	proto.RegisterType((*NonAxMessage)(nil), "axtest.testmessages.NonAxMessage")
}

func init() {
	proto.RegisterFile("src/axtest/testmessages/messages.proto", fileDescriptor_96dc454175151548)
}

var fileDescriptor_96dc454175151548 = []byte{
	// 224 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x2b, 0x2e, 0x4a, 0xd6,
	0x4f, 0xac, 0x28, 0x49, 0x2d, 0x2e, 0xd1, 0x07, 0x11, 0xb9, 0xa9, 0xc5, 0xc5, 0x89, 0xe9, 0xa9,
	0xc5, 0xfa, 0x30, 0x86, 0x5e, 0x41, 0x51, 0x7e, 0x49, 0xbe, 0x90, 0x30, 0x44, 0x8d, 0x1e, 0xb2,
	0x1a, 0x25, 0x79, 0x2e, 0x76, 0x5f, 0x08, 0x5b, 0x48, 0x84, 0x8b, 0xb5, 0x2c, 0x31, 0xa7, 0x34,
	0x55, 0x82, 0x51, 0x81, 0x51, 0x83, 0x33, 0x08, 0xc2, 0x51, 0x52, 0xe0, 0xe2, 0x80, 0x2a, 0x70,
	0x24, 0xa8, 0xc2, 0x89, 0xa0, 0x0a, 0x67, 0x82, 0x2a, 0x5c, 0x08, 0xaa, 0x70, 0x25, 0xa8, 0xc2,
	0x0d, 0x87, 0x0a, 0x79, 0x2e, 0x76, 0xe7, 0xfc, 0xdc, 0xdc, 0xc4, 0xbc, 0x14, 0x1c, 0x0a, 0x74,
	0xb9, 0x44, 0x83, 0x53, 0x73, 0xd2, 0xc2, 0x12, 0x73, 0x32, 0x53, 0x12, 0x4b, 0x32, 0xf3, 0xd2,
	0xf1, 0x2b, 0x37, 0xe6, 0x92, 0x76, 0x4b, 0xcc, 0xcc, 0x49, 0x4d, 0x21, 0x45, 0x93, 0x2c, 0x17,
	0xab, 0x6b, 0x59, 0x6a, 0x5e, 0x09, 0x0e, 0x69, 0x6d, 0x2e, 0x61, 0x54, 0xd3, 0xf0, 0x29, 0x36,
	0xe4, 0x92, 0xc4, 0xe6, 0x00, 0x7c, 0x5a, 0x54, 0xb8, 0x78, 0xfc, 0xf2, 0xf3, 0x1c, 0x2b, 0xf0,
	0xc6, 0xba, 0x93, 0x7e, 0x94, 0x6e, 0x7a, 0x66, 0x49, 0x46, 0x69, 0x92, 0x5e, 0x72, 0x7e, 0xae,
	0x7e, 0x56, 0x6e, 0x62, 0x4e, 0x4e, 0x3e, 0x28, 0x91, 0xe9, 0xe3, 0x48, 0x6b, 0x49, 0x6c, 0xe0,
	0x34, 0x66, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xbd, 0x98, 0xa2, 0xbb, 0x8d, 0x02, 0x00, 0x00,
}
